### ISSUE TITLE
Automated cross-compatibility checking between various implementations

### ISSUE THREAD

**Issue by drewhk** [reactive-streams/reactive-streams-jvm#112]
Apart from the TCK, which is a common point to be validated against, it would be nice to have a test infastructure which plugs together various different implementations and tests that they work together properly.

This ticket might not be strictly in the scope of this project (it is more of a "community" effort), but I found this to be the best place for this proposal.

**Comment by viktorklang** [comment]
This seemed to never be needed. A testament to the quality of the TCK!
