### ISSUE TITLE
Move code out of MD files

### ISSUE THREAD

**Issue by mkiedys** [reactive-streams/reactive-streams-jvm#126]
This is follow-up from PR #125:

@viktorklang wrote:
_(...) what I meant was that I think that sample code should live in compiled files, so that we can catch when it needs to be updated. As such I think all code should be moved out of .mds and put into files and then either imported automatically into the .mds or be linked from the .mds._

**Comment by rkuhn** [comment]
Checking: no change on the github side of things. This is a generic ticket with possibly a different solution, so if somebody has a low-overhead working principle to point at then we should definitely try it out.

**Comment by viktorklang** [comment]
I think we should just link to the example files or the spec classes (now with Java they have their own files).

**Comment by ktoso** [comment]
@reactive-streams @viktorklang so are we planning on doing something with this now?
Tech wise the situation has not changed, we can't `include` files.

**Comment by viktorklang** [comment]
I think this will stay as a "nice-to-have".

**Comment by ktoso** [comment]
Sounds good to me.

**Comment by viktorklang** [comment]
I don't think there's enough need to warrant this Issue. If someone disagrees, please reopen.
