### ISSUE TITLE
remove rule 1:12 (must produce same elements to multiple Subscribers)

### ISSUE THREAD

**Issue by rkuhn** [reactive-streams/reactive-streams-jvm#224]
Rationale: rule 1:11 states that a Publisher may choose to treat multiple Subscribers as either unicast or multicast recipients, but 1:12 forbids the delivery of different stream elements to different subscribers, thereby effectively making the unicast choice useless—the typical use-case would be to have a Publisher set up a new connection to some data source for every new Subscriber, and then it cannot in general guarantee the “same elements” restriction (which might also be unwanted).

Removal of the rule does not actually change the set of permissible behaviors apart from removing the aforementioned conflict, since the word “multicast” sufficiently captures the intent that was behind 1:12.

**Comment by viktorklang** [comment]
@szeiger questions yesterday got me thinking about this as well, and IIRC I think @benjchristensen raised this a while back too.

I don't see how removing 1.12 would cause any problems so :+1: from me.

@reactive-streams/contributors Wdyt?

(I'll have limited connectivity over the next weeks so won't be able to chime in)

**Comment by drewhk** [comment]
It does not affect Akka Streams, but I also think that the rule is confusing. People have to document the exact semantics of their Publishers for multiple subscribers anyway.

+1 for removal.

**Comment by benjchristensen** [comment]
:+1: for removal.
