### ISSUE TITLE
Rule 1.1 vs. dropping/buffering onNext events

### ISSUE THREAD

**Issue by akarnokd** [reactive-streams/reactive-streams-jvm#229]
> §1.1: The total number of ```onNext``` signals sent by a ```Publisher``` to a ```Subscriber``` MUST be less than or equal to the total number of elements requested by that ```Subscriber```´s ```Subscription``` at all times.

RS is biased towards cold ```Publisher```s (not sending anything unless requested)  vs. event sources such as mouse movements (which happen regardless anyone subscribed or requested values).

So given a hot ```Publisher```, does this rule (permit | require) (buffering | dropping) ```onNext``` signals?

#### Example 1
```PublishProcessor``` delivering mouse movements to subscribers. Since mouse can't be backpressured nor is it wise to buffer movements for everyone, ```PublishProcessor``` would either drop events for uninterested (requested == 0) subscribers, or disregard any backpressure and require the use of a downstream operator that drops/buffers (i.e., RxJava's ```onBackpressureDrop``` and ```onBackpressureBuffer```).

#### Example 2
```ReplayProcessor``` accumulates events and replays them to subscribers coming in the middle or after the accumulation phase. This ```Publisher``` has to buffer events and can naturally support backpressure (won't start replaying until requested > 0).

**Comment by ktoso** [comment]
Correct. RS *forces* implementations to either buffer or drop elements.
There is a 3rd option, however it is less useful - you can tear down the stream by onErroring your subscribers when "oh no. I can't buffer anymore, but am not allowed to drop elements! I'll kill myself".

**Comment by drewhk** [comment]
RS is for backpressured stream processing. I am not sure mouse movements should be modeled as RS streams.

**Comment by viktorklang** [comment]
A Hot Publisher will have to decide what to do in case there is no current demand from its Subscribers.
