### ISSUE TITLE
Clarification on createErrorStatePublisher

### ISSUE THREAD

**Issue by purplefox** [reactive-streams/reactive-streams-jvm#235]
Hi,

When extending PublisherVerification I need to implement createErrorStatePublisher() but unfortunately I can't find anything in the README or Javadoc that explains what this should return or what the purpose of this method is.

I can guess it should return a publisher that should create some kind of error condition, but further than that I am lost.

Any pointers would be appreciated :)

**Comment by ktoso** [comment]
Hey there,
The best description is JavaDoc I think:
```java
  /**
   * Return a Publisher in {@code error} state in order to run additional tests on it,
   * or {@code null} in order to skip them.
   */
  public abstract Publisher<T> createErrorStatePublisher();
```

As it said :-) We have additional tests for "errored publishers", i.e. that it should signal `onError` and things like that. If you want these tests to be run, return such publisher here.

The tck/README.md does give examples and a slight explanation but perhaps it should be revamned anyway as we discussed in the other topic.

**Comment by purplefox** [comment]
Ok, but that still doesn't tell me what the expected behaviour of that publisher should be ;)

"Return a publisher in error state" doesn't convey much meaning unless you define what "error state" means.

**Comment by ktoso** [comment]
It is such publisher that will emit onError.

These tests serve testing that whatever scheduling mechanisms you have in place, they also work for "immediately failed sources". Simplest Publisher is to onError right away, if you're an async impl you may have to go through some scheduling to emit the error.

See here on order of allowed events: https://github.com/reactive-streams/reactive-streams-jvm#api-components

So it should:

```scala
val s: Subscription = ??? // this can be a "empty subscription" as we know we'll onError anyway in a second:
subscriber.onSubscribe(s)
s.onError()
```

Notice that it is REQUIRED to signal the onSubscribe. We had a long discussion if it's required or not, and this is the current spec (not likely to change), see commit here in case you want more rationale why onSubscribe is needed https://github.com/reactive-streams/reactive-streams-jvm/commit/10b6db28c6d44179ab9f583a2c88875cf6c59203

// Hah another catch in the tck/README.md - the example there violates the spec. I really must make time to update the TCK README, it seems the last spec changes were not reflected in it. Thanks for complaining about "error state", you're right that it's not defined anywhere.

Hope this helps!

**Comment by purplefox** [comment]
So to clarify:
The required behaviour is for the implementation to perform it's normal subscribe, and then to signal an error by calling s.onError().
That's basically all the information I was looking for. Would be great to have that added to the readme :)

**Comment by ktoso** [comment]
Definitely, will add :-)
Your questions here help tremendously to flesh out these missing infos / docs, thanks again!

**Comment by viktorklang** [comment]
@ktoso Status here?

**Comment by ktoso** [comment]
Status is there's a PR awaiting your feedback https://github.com/reactive-streams/reactive-streams-jvm/pull/241 :-)

**Comment by ktoso** [comment]
Please close this issue as https://github.com/reactive-streams/reactive-streams-jvm/pull/241 was merged :-)

// cc @viktorklang

**Comment by viktorklang** [comment]
Affirmative
