### ISSUE TITLE
Vert.x TCK compliance

### ISSUE THREAD

**Issue by purplefox** [reactive-streams/reactive-streams-jvm#238]
Hi all,

Not sure if this is the right place to post this, but apparently the google group is not in use any more so I wasn't sure where else.

Just thought you'd like to know I've got the TCK tests passing (*) against the Vert.x implementation :)

https://vertx.ci.cloudbees.com/job/vert.x3-reactive-streams-tck/1/testReport/io.vertx.ext.reactivestreams.tck/

(*) -
1. I have put a hack in place to work around https://github.com/reactive-streams/reactive-streams-jvm/issues/233 so it passes
2. I haven't implemented the Whitebox tests as I couldn't figure out what the TCK was expecting me to do with the probe thingies
3. I couldn't figure out what the TCK wanted me to return in PublisherVerification.createErrorStatePublisher so I'm just returning null for now which seems to cause the tests to be disabled.

**Comment by purplefox** [comment]
So if I can resolve 1 and 3 (and maybe 2), then I think we are good to go :)

**Comment by viktorklang** [comment]
@purplefox Do your bullet points seem addressed by the open PRs? :)
