### ISSUE TITLE
Approach to high-performance streaming

### ISSUE THREAD

**Issue by emil-mi** [reactive-streams/reactive-streams-jvm#248]
Hi all,

Is there some plan/recommended approach to address some performance scenarios. More specifically:
* how to orchestrate a flow of data to ensure "zero-copy" behaviour?
* how to handle streams that can seek?

Thank you!

**Comment by smaldini** [comment]
I think it will be implementation driven, we try to do so in http://github.com/reactor/reactor-core

**Comment by viktorklang** [comment]
@emil-mi 

Thanks for your question!

Just to add to @smaldini's answer:

We've benchmarked possible implementations to be able to deliver sustained rates of over 100mops/s and as such the most likely bottleneck will be business logic overhead etc.

As for seeking behavior that is completely left up to your implementation to provide Publishers that will start from a given offset. Or did you mean something different.

**Comment by emil-mi** [comment]
Please consider the following scenarios:
 1. You want to transform a stream of bytes (read from an URL, apply some byte->byte transform, write to some file). Obviously you want to work at once with as many bytes as possible (since 100mops/s translates to a data rate of 100mbps that's not impresive).
* What is the type of T in Subscriber<T> in this case? I would expect to be byte[], or some type that models a collection of bytes (a "buffer").
* What does the n in Subscription.request(n) means in this case? The number of bytes or the number of "buffers".
* More importantly: how can one insure that memory for those buffers is allocated only when needed such as to reduce the pressure on the GC (or the allocator)?
 2. I want to parse some data encoded in fixed length segments (think records or type-length-value protocols where the length of the data is known beforehand) so I lay out my data flow like 
`Publisher<byte> -> SkipFilter(number of bytes to discard) -> TransformFilter -> Consumer`.
Is there a way to enable "accelerated" operations in the case that the Publisher supports such "null reads"?

**Comment by viktorklang** [comment]
Hi @emil-mi,

>You want to transform a stream of bytes (read from an URL, apply some byte->byte transform, write to some file). Obviously you want to work at once with as many bytes as possible (since 100mops/s translates to a data rate of 100mbps that's not impresive).

You definitely do not want to work on as many bytes as possible, for an unbounded sequence of bytes that will blow your heap faster than you can say "back pressure".

>What is the type of T in Subscriber in this case? I would expect to be byte[], or some type that models a collection of bytes (a "buffer").

That's completely up to the Subscriber, but it would be some kind of `ChunkOfBytes`.

>What does the n in Subscription.request(n) means in this case? The number of bytes or the number of "buffers".

Always the number of Ts, in this case `number of ChunkOfBytes`

>More importantly: how can one insure that memory for those buffers is allocated only when needed such as to reduce the pressure on the GC (or the allocator)?

The Publisher is allowed to make these decisions however it pleases.


>I want to parse some data encoded in fixed length segments (think records or type-length-value protocols where the length of the data is known beforehand) so I lay out my data flow like Publisher<byte> -> SkipFilter(number of bytes to discard) -> TransformFilter -> Consumer. Is there a way to enable "accelerated" operations in the case that the Publisher supports such "null reads"?

Worth keeping in mind is the goal of Reactive Streams:

*"Reactive Streams is an initiative to provide a standard for asynchronous stream processing with non-blocking back pressure on the JVM."*

If you have no need for asynchrony (i.e. the consumer can always run at the speed of the producer without having to ever block) then simple function composition or method calling will work just fine; there is no need for back pressure. What's good is that Reactive Streams -works- for that use-case as well (see [this](https://github.com/reactive-streams/reactive-streams-jvm#asynchronous-vs-synchronous-processing) but of course poly or megamorphic callsites will -never- be as fast as a fully inlined and unrolled while loop.

In your example perhaps the method that creates the Publisher takes an offset to where to skip into that Publisher, not all may support that feature efficiently anyway.

Cheers,
√

**Comment by emil-mi** [comment]
Hi,

I think I have enough information to close this question. My understanding is that:
 1. The Publishers are the ones responsible for allocating memory in the system.
 2. A Processor can modify in-place and then forward the resources it receives as arguments to the onNext signal or it can create new objects to send downstream (that is on his Publisher side).
 3. The system handles back-pressure with the credit based flow control scheme but it does not use batching to deliver more elements with a single onNext call. Nevertheless, this behaviour can be implemented by a protocol between concrete implementations of Publisher and Subscriber that is outside the scope of this project (ex. cast the Subscription to some other interface that has the required methods).
 4. Management of memory is the responsibility of the garbage collector. There is no way to implement a pool of <T>s to be used in this specification. This can be implemented outside the scope of this specification by an appropriate design of the class T used (ex. implement ```AutoCloseable``` and have the Subscribers call the required method when done with the instance).
 5. To skip elements from a Publisher you must use an implementation detail that is outside the scope of this specification (ex. either start the Publisher from an offset or implement some ```seek``` method on the Subscription). Because of rule 2 for Subscribers, it is not ok to do the IO work lazily  when the Subscriber accesses the <T> in ```onNext``` (you could Publish a "handle" to the bytes of a file stream starting from an offset and do the actual reading if ever those bytes are accessed but that would mean that ```onNext``` or some other method that does the processing could take a lot of time and mess with the reactive property of the system).

I hope I got a correct understanding of the issues touched. I want to thank you all for your patience and wish you all the best.

**Comment by viktorklang** [comment]
>The Publishers are the ones responsible for allocating memory in the system.

Yes and no, imagine a Subscriber which lives on another JVM than the Publisher, onNext etc will transform the element, put it on the wire and reconstruct it at the other end.

>A Processor can modify in-place and then forward the resources it receives as arguments to the onNext signal or it can create new objects to send downstream (that is on his Publisher side).

Correct

>The system handles back-pressure with the credit based flow control scheme but it does not use batching to deliver more elements with a single onNext call. Nevertheless, this behaviour can be implemented by a protocol between concrete implementations of Publisher and Subscriber that is outside the scope of this project (ex. cast the Subscription to some other interface that has the required methods).

Correct

>Management of memory is the responsibility of the garbage collector. There is no way to implement a pool of Ts to be used in this specification. This can be implemented outside the scope of this specification by an appropriate design of the class T used (ex. implement AutoCloseable and have the Subscribers call the required method when done with the instance).

You can of course implement a pool, but it needs to be a pool of immutable objects, otherwise correct!

>To skip elements from a Publisher you must use an implementation detail that is outside the scope of this specification (ex. either start the Publisher from an offset or implement some seek method on the Subscription).

To skip elements from a publisher you can also just drop them.

>Because of rule 2 for Subscribers, it is not ok to do the IO work lazily when the Subscriber accesses the T in onNext (you could Publish a "handle" to the bytes of a file stream starting from an offset and do the actual reading if ever those bytes are accessed but that would mean that onNext or some other method that does the processing could take a lot of time and mess with the reactive property of the system).

Yes, onNext is a *signal*, it is not intended to process the element but to transport it to the Subscriber so that it can be processed there. There is an exception in place for Subscribers that will not impact the responsiveness of the Publisher.
