### ISSUE TITLE
Urgent: Everyone update to 1.0.0.RC4!

### ISSUE THREAD

**Issue by viktorklang** [reactive-streams/reactive-streams-jvm#257]
@reactive-streams/contributors Please update your implementations to 1.0.0.RC4 ASAP and give feedback so we can make sure there are sufficient number of TCK-passing implementations when we release 1.0.0.final!

**Comment by ktoso** [comment]
Akka confirms to pass RC4: https://github.com/akka/akka/pull/17116 :-)

**Comment by smaldini** [comment]
Passing RC4 too https://build.spring.io/browse/REACTOR-CORE2-404

**Comment by viktorklang** [comment]
@smaldini Great news! And thanks a lot for pushing the RC4!

**Comment by benjchristensen** [comment]
Ack on the request ... will respond back.

**Comment by viktorklang** [comment]
Roger.

**Comment by benjchristensen** [comment]
@alkemist [did the upgrade](https://github.com/ReactiveX/RxJavaReactiveStreams/issues/142) for RxJavaReactiveStreams to RC4 and it is passing the tests. 

- RC4 binary: https://travis-ci.org/ReactiveX/RxJavaReactiveStreams/jobs/56833217#L395
- Test results: https://travis-ci.org/ReactiveX/RxJavaReactiveStreams/jobs/56833217#L595

**Comment by viktorklang** [comment]
Thanks @benjchristensen & @alkemist for verifying!
Things are really looking good!

@purplefox Everything OK with RC4 on your end?

**Comment by alkemist** [comment]
FYI - I'm hanging off on rc4 and waiting for #259 for Ratpack.

**Comment by viktorklang** [comment]
Aiming to release RC5 tomorrow as we'll most likely have all implementations passing the TCK.
Then we issue 1.0.0.final if no blockers arise in ~2weeks. Sounds good @reactive-streams/contributors ?
