### ISSUE TITLE
add plugins to build.gradle for IDE convenience?

### ISSUE THREAD

**Issue by davidmoten** [reactive-streams/reactive-streams-jvm#258]
To import the project into eclipse I needed to 

* clone the repo
* edit ```build.gradle``` to include the line ```apply plugin: 'eclipse'```
* run ```./gradlew eclipse```
* import into eclipse
*  ```git checkout .``` to remove my changes. 

Just wondering if adding a couple of convenience lines to ```build.gradle``` would be acceptable:

```
apply plugin: 'eclipse'
apply plugin: 'idea'
```

**Comment by viktorklang** [comment]
Hi Dave,

I think mixing IDE concerns into a specific project's definition is mixing
concerns.

I recommend using something like this:
http://stackoverflow.com/questions/11567786/global-plugins-in-gradle

-- 
Cheers,
√

**Comment by davidmoten** [comment]
I quite agree. That was just the tip I was after, thanks!

**Comment by viktorklang** [comment]
You're most welcome!

-- 
Cheers,
√
