### ISSUE TITLE
setup publishing procedure

### ISSUE THREAD

**Issue by rkuhn** [reactive-streams/reactive-streams-jvm#264]
One possibility is to automate it using travis and bintray as [proposed by Ben](https://github.com/reactive-streams/reactive-streams-jvm/pull/220#issuecomment-83039724).

**Comment by viktorklang** [comment]
I think the infrequency of releases removes the need for automating them. Closing. (unless someone wants to automate, in which case it can be reopened as a PR is opened ;))
