### ISSUE TITLE
2.4 a bit confusing

### ISSUE THREAD

**Issue by davidmoten** [reactive-streams/reactive-streams-jvm#266]
I find 2.4 a bit confusing. Its form is different from all the other rules (There's no "A Subscriber MUST"), rather it's "these methods MUST" and I don't know if I'm seeing a mistake or intent. Can someone clarify its meaning for me?

>Subscriber.onComplete() and Subscriber.onError(Throwable t) MUST consider the Subscription cancelled after having received the signal.

**Comment by viktorklang** [comment]
@davidmoten This is also a good use-case for the "explaining the intent" Issue.

2.4 is there for symmetry with 1.6, as a spec optimization it could probably be folded into 2.3, but given the impeding 1.0.0.final and that it wouldn't add any value to make the change, I'd say it's not worth it.

**Comment by viktorklang** [comment]
@davidmoten I think this ought to be folded into the explanations for each rule, are you OK with me closing this in the mean time?

**Comment by davidmoten** [comment]
Sure.
