### ISSUE TITLE
I don't quite understand 2.2; perhaps it would benefit from clarification

### ISSUE THREAD

**Issue by mhurne** [reactive-streams/reactive-streams-jvm#273]
2.2 states:

"If a Subscriber suspects that its processing of signals will negatively impact its Publisher's responsivity, it is RECOMMENDED that it asynchronously dispatches its signals."

Does this mean:

1) If a Subscriber suspects that its processing of signals will negatively impact its Publisher's responsivity, it is RECOMMENDED that *the Subscriber asynchronously dispatches its signals to the Publisher*.

or

2) If a Subscriber suspects that its processing of signals will negatively impact its Publisher's responsivity, it is RECOMMENDED that *the Subscriber asynchronously dispatches the signals it receives from the Publisher*.

Or is neither of those interpretations accurate? Perhaps this hinges on my (lack of) understanding of the word "dispatches."

**Comment by viktorklang** [comment]
Hi Matt,

Thanks for raising the question!

The rule means that synchronous Subscribers are only OK as long as they do
not impact the caller negatively (the caller being the Publisher), so for
all other Subscribers, the processing of signals must be done
asynchronously.

See AsyncSubscriber in the examples for more details,
also AFAIR there's a bit of elaboration on the topic of signals in the spec
doc.

Does any of that help?

-- 
Cheers,
√

**Comment by mhurne** [comment]
Ok - so it sounds like (2) in my first comment is the correct interpretation?

**Comment by viktorklang** [comment]
Yes, so it seems :)

-- 
Cheers,
√

**Comment by viktorklang** [comment]
@mhurne Can we close this?

**Comment by mhurne** [comment]
Sure - I suggest clarification of this point in the documentation, but if you'd prefer to leave it as-is feel free. Thanks!

**Comment by viktorklang** [comment]
We'll update the spec with a clarification of the intent of each rule, to guide the reader.
