### ISSUE TITLE
TCK for implementations of indiscrete streams

### ISSUE THREAD

**Issue by jroper** [reactive-streams/reactive-streams-jvm#283]
One of the things that bugs me about the TCK verification of my implementation of Netty Reactive Streams is that it's impossible to verify it against Netty's prime use case - handling TCP streams.  Rather, I have to insert a handler into the Netty pipeline that produces discrete elements.  This handler may be hiding bugs, in fact it did hide a bug, I wasn't reading when the channel opened, I was only reading when the handler was inserted in the chain, which worked fine in my simplified pipeline with my own handler producing discrete elements, since in that setup there was no concept inserting the handler in the chain was the same thing as opening the channel.

The problem is TCP streams are indiscrete streams of data, when a publisher of such a stream publishes elements, it will publish some sort of byte buffer, but will have very little or no control over how many bytes are in that byte buffer - usually it will only have a configured maximum that it will read.  So when the TCK requests to create a publisher of 8 elements, there's no way to meet that contract, you can create the publisher, open a socket, send some bytes down it, but you've got no idea whether that will cause the publisher tol produce one element, or one element for each byte, or anything in between.  The same problem exists for subscribers, you can create several byte buffers when the TCK asks, it will publish that, but then when you read from the socket that the subscriber writing its data to, you may get all the data in one read, or you may get it in many reads.

This problem will be more evident when, for example, someone creates a reactive streams implementation on Servlet 3.1.  Unlike Netty, Servlet 3.1 *only* supports indiscrete byte streams, so it will be impossible to use the TCK to verify that implementation.

So I think we should consider creating versions of the TCK (in addition to the existing ones) for indiscrete streams.

For the publisher, a whitebox verification would be required.  This would have a puppet with the following methods:

```java
/**
 * Cause the publisher to be able to produce at least one element.
 * 
 * @return The data that was written to the publisher.
 */
T produce();

/**
 * Cause the publisher to eventually complete.
 */
void complete();
```

It would also require a method to check whether a set of elements published is contained in another set of elements, eg:

```java
/**
 * Check whether the data contained in the expected elements is a prefix of the data contained
 * in the received elements.
 * 
 * @returns null if it's not, otherwise a single element that represents the (possibly empty) tail
 *     of the received data that wasn't in the expected prefix.
 */
T isPrefix(Collection<T> expected, Collection<T> received);
```

Using these interfaces, I think a publisher whitebox TCK could be implemented to test everything except error handling.  It is very difficult to force a socket to reliably throw an error asynchronously.  If you write to it while closed, that will throw an error, but synchronously.  Getting it to asynchronously produce an error would probably require writing to it at the same time as the remote end closes.  So creating a failed publisher is probably not possible.

Similar changes would need to be made to the whitebox subscriber TCK, rather than verifying that discrete elements were received, it should verify that lists of data were received with the help of the `isPrefix` method.

**Comment by viktorklang** [comment]
@jroper The TCK is only intended to verify the conformance to the Reactive Streams Spec, it's not intended as a general RS implementation verifier (i.e. testing other behavior outside of the spec).
So, before we explore changing this here, I must ask whether your use-case perhaps is better addressed as specific tests for the netty implementation? (as Akka has specific tests to verify TCP integration into Akka Streams for instance)

**Comment by viktorklang** [comment]
Would love to hear what the other @reactive-streams/contributors think about this!

**Comment by jroper** [comment]
How does Akka test its TCP integration?

I'm not trying to verify the RS implementation, I'm trying to verify the implementations conformance to the spec.  And it's not a huge problem for the Netty implementation, but it will be a huge problem for things like a Servlet 3.1 RS implementation.  The problem is not that the implementation can't be fully tested by the TCK, the problem is that the TCK could not be run at all against the implementation, since it is impossible to, for example, implement the contract required by `createPublisher(long elements)` in the publisher verification.

I mean, I suppose I could mock the Servlet 3.1 interfaces completely, including mocking the input streams etc so that reads always return a deterministic number of bytes... but then what am I verifying?  Not a Servlet 3.1 RS implementation, but an RS implementation of whatever my mocks do.  It wouldn't be true to say that this is a TCK verified Servlet 3.1 RS implementation, since the TCK would never have run against a verified Servlet 3.1 implementation.

**Comment by viktorklang** [comment]
@jroper Check the tests folder of the Akka Streams for TCP.
I understand the predicament, but the question is how we can improve this. nondiscrete streams are just one aspect, what about things like Publishers that always fail, Publishers that never emit, Publishers that are always empty etc. The full range of RS Spec verification cannot apply to all implementations. Ideally I'd like to have a TCK which would Just Work(tm) and guide people along the right path. We'll probably never get there, but I'm all ears for concrete proposals on how to improve the current situation.
The biggest benefit of the TCK is that it provides an authoritative source of rule application for the RS spec, mitigating some of the risks of interpretation of the spec by a reader/implementor. Something that's been on my table for a while is to create, for each rule, a section of rationale for the rule, to assist implementors in understanding the reason behind the rules, for deeper understanding. This will of course not solve your problem here, but perhaps set more accurate expectations.

Thanks for raising all these great questions and suggestions, this kind of feedback is invaluable, James!

**Comment by viktorklang** [comment]
Nothing to do here
