### ISSUE TITLE
Clarification on multiple subscribers needed ..

### ISSUE THREAD

**Issue by RuedigerMoeller** [reactive-streams/reactive-streams-jvm#284]
I implemented multiple subscribers using a "wait-for-slowest-subscriber" policy. This means if of 2 subscribers only one sends "credits" via request(N), no message will be sent. So credits = Min(credits of subscribers)

this makes 

`required_mustRequestFromUpstreamForElementsThatHaveBeenRequestedLongAgo()`
and `required_spec104_mustCallOnErrorOnAllItsSubscribersIfItEncountersANonRecoverableError()` fail.

But "wait-for-slowest-subscriber" (with optional timout/forced cancel policy) actually does not violate the spec, isn't it ?

**Comment by ktoso** [comment]
Hi @RuedigerMoeller, thanks a lot for catching this - you're absolutely correct.
These tests assume too much about the publisher - namely that it just signals the elements once demand comes in. I've skimmed the impls now and it seems that amending them won't be too hard - I'll send in a PR soon to fix this.

**Comment by RuedigerMoeller** [comment]
Thanks for the quick response :). Kudos for the test suite, it discovered an awful lot of issues in my initial implementation ..
Hoping to provide a hp multiple-transport reactive-streams remoting plug soon :)

**Comment by ktoso** [comment]
Addressed one part of the issue in this PR: https://github.com/reactive-streams/reactive-streams-jvm/pull/287
Will try to make time and figure out `required_mustRequestFromUpstreamForElementsThatHaveBeenRequestedLongAgo` soon.

**Comment by RuedigerMoeller** [comment]
Hi, afair `required_mustRequestFromUpstreamForElementsThatHaveBeenRequestedLongAgo ` had the same problem in the test prologue.
Will unignore the testcase and retry when out of office ;)

**Comment by viktorklang** [comment]
@ktoso Was this fixed and merged?

**Comment by viktorklang** [comment]
@ktoso Sorry, I see the PR…

**Comment by ktoso** [comment]
Yeap, it's that one which I need to get back to: https://github.com/reactive-streams/reactive-streams-jvm/pull/287

**Comment by viktorklang** [comment]
@RuedigerMoeller Please see #414. Will be released in 1.0.2 which is due before end-of-year!
