### ISSUE TITLE
Enhancement proposal for 1.1

### ISSUE THREAD

**Issue by RuedigerMoeller** [reactive-streams/reactive-streams-jvm#285]
just finished https://github.com/RuedigerMoeller/kontraktor/blob/trunk/modules/reactive-streams/README.MD  (passes tck). Note that remotable reactive streams come "for free" via generic kontraktor remoting, its not that I want to anticipate pending/ongoing spec in this area.

What I am missing is kind of a sequencing scheme. This would enable a lot of features/components such as message persistence/failure recovery/guaranteed delivery/reactive-streams MQ broker, still keeping the interface lean.

something along the lines of

``` java
interface SequencedMessage {
   long getSequence();
   void setSequence(); // required to allow resequencing (aggregating intermediates)
}

interface SequencedPublisher extends Publisher {
     void subscribe( Subscription, long sequence);
}

// alternatively 

interface SequencedSubscriber extends Subscriber {
    long getStartSequence();
}
```

Especially when trying to extend reactive streams to mobile or browser clients, apps have to able to deal with disconnects (or hibernating in case of mobile clients).

**Comment by viktorklang** [comment]
Hi @RuedigerMoeller,

the seqno approach has been considered (atleast in my head) for `reactive-streams-io` as it would allow for a higher degree of resilience when going over a lossy medium.

As such it could be implementable at a level above:

`someSource.createPublisher(offset).subscribe(subscriber)`, which would allow any-old Subscriber to take advantage of the replayability of the source.

Does that sound agreeable? Would love to hear your thoughts.

(also ping @tmontgomery)

**Comment by RuedigerMoeller** [comment]
the `someSource.createPublisher(offset)` looks more elegant, however the client still needs a standard way of retrieving (setting) a sequence from/to a message.

The on-top approach has the disadvantage that one cannot provide generic resilence components  such as application-transparent reconnect, replayable message store, aggregating multiple stream sources or hot-hot-redundancy based failover.

IMO in general its favourable to push resilence/failover to the lowest layer possible. Reactive streams to me seems like the ideal level to provide some "magic" independent of underlying transport+encoding.

**Comment by viktorklang** [comment]
Hi @RuedigerMoeller,

Perhaps the easiest way forward is to have a more fleshed out proposal, so it's possible to see how the semantics would be.

**Comment by RuedigerMoeller** [comment]
Hi @viktorklang , I think I can come up with a more detailed proposal within next 2 weeks. I aim to define this as kind of an "extension" without the need to change existing API.

**Comment by viktorklang** [comment]
Hi @RuedigerMoeller, looking forward to reading it :)

**Comment by RuedigerMoeller** [comment]
hi, put it here:
https://github.com/RuedigerMoeller/reactive-streams-sequenced-proposal/blob/master/

adding sequenced and keyed messages would widen the applicability of reactive streams drastically  e.g. abstracting away network topology + reliability, persistance (last value cache), message replay for generic HA (bootstrap new instance by replay), ...

**Comment by viktorklang** [comment]
Thanks for the update! I hope I'll have time to have a look at it over the weekend!

**Comment by viktorklang** [comment]
@RuedigerMoeller It is not public/I don't have access to it

**Comment by pvorb** [comment]
@viktorklang It seems to be public now.

**Comment by RuedigerMoeller** [comment]
Hm .. I actually never changed visibility. Do you need write access ?

2015-08-25 23:21 GMT+02:00 Paul Vorbach <notifications@github.com>:

**Comment by viktorklang** [comment]
this link is a 404

-- 
Cheers,
√

**Comment by RuedigerMoeller** [comment]
Double checked this (with logging out)

https://github.com/RuedigerMoeller/reactive-streams-sequenced-proposal

2015-08-26 19:43 GMT+02:00 Viktor Klang (√) <notifications@github.com>:

> this link is a 404
>
> --
> Cheers,
> √

**Comment by viktorklang** [comment]
@RuedigerMoeller Yep, that link works!

**Comment by greg-a-atkinson** [comment]
Hi @viktorklang @RuedigerMoeller 

I would like to second this proposal.

From the specification, it is true that with a stream it is possible to "process a potentially unbounded number of elements," but the elements for a stream are only unbounded towards the future, following a specific first element, and can therefore be sequenced and indexed explicitly.

A sequenced stream provides the consumer with the important ability to seek to a specific position in the stream. Presently, in version 1.0 of RS, the position in the stream at which the consumer joins is implicit and represents the next unconsumed message. The ability to rewind a stream importantly allows for the implementation of guaranteed delivery patterns, at least with duplication. This is not incompatible with the present interface as a stream that cannot be moved could simply forward an error to the consumer inducting as much. (Skipping forward in a stream is easily implemented by not emitting the events in between, but has arguably limited use cases.)

Enhancing the RS version 1.0 interfaces and specification for this requirement has multiple options with varying advantages and trade-offs. @RuedigerMoeller's interfaces add flexibility for future changes, but with the trade-off of object creation as opposed to overloading the relevant methods with sequence parameters. I am not advocating a specific solution.

```
Subscription
void request(long numberOfElements)
void request(long numberOfElements, long fromSequence)

Subscriber
void onNext(V value)
void onNext(long sequence, V value)
void onNext(long sequence, K key, V value)
```

One of the challenges to implementing this enhancement is to consider how streams are concatenated and what this means for their sequencing.

A good example of where sequencing and offsets have been applied are in Kafka's consumer interface for its topic partitions where the consumer has a high degree of control as to where it consumes from and when it is able to change its position. Not all publishers are suited to changing stream positions, but those who own the data, like database and middleware services, could enable particularly effective use cases from the ability to do so.

Reactive streams show a lot of promise and their adoption and implementation by various third-parties is encouraging. Thanks for the great work.

Kind regards,
Greg Atkinson

**Comment by RuedigerMoeller** [comment]
@greg-a-atkinson thx for supporting. Note that my proposal does not force additional object creation. A message class might implement `SequencedMessage` and `return this` in the `payload()` method + provide a sequence setter. 
So existing streams can be sequenced using wrapper classes, new / efficient messages might directly implement the interface at cost of being mutable (sequence).

**Comment by greg-a-atkinson** [comment]
Hi @RuedigerMoeller 

Thanks for your response. You're quite right, object creation could be avoided and the interface approach could well be better than the parameter approach. Nevertheless, I'm far more interested applying this feature than I am about the implementation and its optimisations, which I'll leave to those who feel strongly about it. So while I'm here, +1 for this proposal.

Kind regards,
Greg Atkinson

**Comment by viktorklang** [comment]
@RuedigerMoeller Quite some time has (unfortunately) passed here. Are you still interested in this proposal?
