### ISSUE TITLE
Support for Scala.js

### ISSUE THREAD

**Issue by alexandru** [reactive-streams/reactive-streams-jvm#291]
Hi folks,

[Scala.js](http://www.scala-js.org/) needs these interfaces as well. For example, as part of the [Monifu](https://github.com/monifu/monifu) project, to get around it on top of Scala.js, I had to [duplicate the interfaces](https://github.com/monifu/monifu/tree/v1.0-RC1/monifu/js/src/main/scala/org/reactivestreams).

A Scala.js specific package should be compiled and deployed on Maven Central. Such a package will be suffixed, in Scala style, with `_sjs0.6_2.11`, which indicates that this package is for Scala.js version 0.6.x and Scala 2.11, like so:

```xml
<dependency>
  <groupId>org.reactivestreams</groupId>
  <artifactId>reactive-streams_sjs0.6_2.11</artifactId>
  <version>1.0.0</version>
</dependency>
```

I'm interested in contributing to make this happen, but not sure how to proceed:

1. are you interested?
2. should this be a separate repository?
3. does it need its own TCK?

Thanks,

**Comment by alexandru** [comment]
Ping. No input, thoughts on this? Do you think it's a bad idea to publish the Scala.js package?

**Comment by ngbinh** [comment]
:+1:

**Comment by viktorklang** [comment]
I'm sorry for the lack of response, for some reason I stopped getting the
notifications.

I'll have a look and get back to this.

-- 
Cheers,
√

**Comment by viktorklang** [comment]
I'm not sure the best way to proceed.
What about creating a `reactive-streams-scalajs` repository under `reactive-streams` and have it hosted there?

What are the plans for it, how would one use it, can one use other implementations? If one is supposed to use it for implementing the spec then I don't see how it would work without a TCK, how would that be possible to migrate without risking the scalajs version to deviate?

Let me know what you propose, I'm curious to hear more.

**Comment by alexandru** [comment]
I'm personally fine with creating a `reactive-streams-scalajs` repository.

Scala.js lives in two worlds. It allows for libraries that work both on top of the JVM and on top of JS. "Isomorphic" as the kids are calling it :-) For my personal use-case, I don't need a Scala.js TCK because the reactivestreams.org contract is tested on top of the JVM. But if you think a TCK is needed, then I'm interested in helping with one.

The gain is the same as on top of the JVM, which is interoperability between libraries. The only problem is that Scala.js libraries will have to interoperate with pure Javascript stuff, if `reactive-streams-js` ever happens. But I wager that the interfaces in `reactive-streams-js` will be similar.

**Comment by viktorklang** [comment]
@alexandru If the current TCK can be used then I don't see why a "new" TCK would be needed.

A `reactive-streams-scalajs` repo would be easy to set up, would you want to run it?

**Comment by alexandru** [comment]
@viktorklang the current TCK can be used for mixed libraries, which I think will represent the majority. A Scala.js-compatible TCK would probably be nice in the long run, but it depends on whether there's going to be demand for it.

For now publishing those interfaces is cheap.
Yes, I'd be interested in running the new repo.

**Comment by viktorklang** [comment]
I've creates the reactive-streams-scalajs repo and invited you to the
administration team of that repo.

On Tue, Feb 9, 2016 at 1:53 PM, Alexandru Nedelcu <notifications@github.com>
wrote:

> @viktorklang <https://github.com/viktorklang> the current TCK can be used
> for mixed libraries, which I think will represent the majority. A
> Scala.js-compatible TCK would probably be nice in the long run, but it
> depends on whether there's going to be demand for it.
>
> For now publishing those interfaces is cheap.
> Yes, I'd be interested in running the new repo.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/reactive-streams/reactive-streams-jvm/issues/291#issuecomment-181852720>
> .
>



-- 
Cheers,
√

**Comment by alexandru** [comment]
:+1: thanks, I've joined :)

**Comment by viktorklang** [comment]
Perfect. I think the first task is to set it up like the -jvm one (LICENSE,
CONTRIBUTING.md, COPYING, CopyrightWaivers.txt etc) would you mind doing
that (I'll review the PR of course).

On Wed, Feb 10, 2016 at 4:39 PM, Alexandru Nedelcu <notifications@github.com
> wrote:

> [image: :+1:] thanks, I've joined :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/reactive-streams/reactive-streams-jvm/issues/291#issuecomment-182431631>
> .
>



-- 
Cheers,
√

**Comment by alexandru** [comment]
Yes, I will do the setup.

**Comment by viktorklang** [comment]
Excellent, thanks!

On Wed, Feb 10, 2016 at 4:50 PM, Alexandru Nedelcu <notifications@github.com
> wrote:

> Yes, I will do the setup.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/reactive-streams/reactive-streams-jvm/issues/291#issuecomment-182440061>
> .
>



-- 
Cheers,
√
