### ISSUE TITLE
Create RS <-> JDK9 bridge jar

### ISSUE THREAD

**Issue by viktorklang** [reactive-streams/reactive-streams-jvm#294]
Reactive Streams are available in JDK9 inside: `java.util.concurrent.Flow`.
Providing converters between org.reactivestreams.\* and java.util.concurrent.Flow.\* would be quite useful.

I propose to add a subproject/jar to the reactive streams project.

**Comment by akarnokd** [comment]
Sounds good but IDE support for JDK 9 is limited, at least Eclipse can't properly use a JDK 9 installment. Same may be true with travis: no `oraclejdk9` yet therefore some sudo trickery may be required.

**Comment by viktorklang** [comment]
@akarnokd That's a good point, it ought to be possible to install the jdk9 from java.net and compile-package-publish locally.

**Comment by ktoso** [comment]
Figuring out how to use JDK9 with gradle may be tricky as well, there is some support coming https://github.com/gradle/gradle/blob/master/design-docs/jdk9-support.md though I wasn't able to make it work in the hour I tried now, needs some more research how to use it.

**Comment by viktorklang** [comment]
I wonder if `sbt` will be able to use jdk9 OOTB.

**Comment by ktoso** [comment]
> I wonder if sbt will be able to use jdk9 OOTB.

Currently no.

And it's a bit more than "using jdk9", we need to be able to compile `module-info.java` into `module-info.class`. Here's a sample project and how to use javac to compile: https://github.com/ktoso/jdk9-module-sandbox

**Comment by smaldini** [comment]
Good idea we already do that with reactor and it actually passes the normal TCK: Publishers.convert(Flow.Publisher) (not sure the other way is that useful). That would be great to get that in some common jar indeed. However I failed a few tests with SubmissionPublisher so worth having a common look!

**Comment by akarnokd** [comment]
> However I failed a few tests with SubmissionPublisher so worth having a common look!

Is there something wrong with `SubmissionPublisher`?

**Comment by akarnokd** [comment]
[Here is](https://gist.github.com/akarnokd/8f1a3e31882c076c704f) a single utility class that does the conversions.

**Comment by viktorklang** [comment]
Nice one, David!

It would be useful having the converters also introspected the parameters
to avoid nesting.

if (rsPublisher instanceof Flow.Publisher) return
(Flow.Publisher<T>)rsPublisher;
else …

On Wed, Nov 11, 2015 at 4:58 PM, David Karnok <notifications@github.com>
wrote:

> Here is <https://gist.github.com/akarnokd/8f1a3e31882c076c704f> a single
> utility class that does the conversions.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/reactive-streams/reactive-streams-jvm/issues/294#issuecomment-155825963>
> .
>



-- 
Cheers,
√

**Comment by akarnokd** [comment]
If one implements both APIs, it should show up in the type and there is no need to call the conversion methods.

**Comment by viktorklang** [comment]
toFlow(toReactive(flowA)) should return flowA

-- 
Cheers,
√

**Comment by akarnokd** [comment]
In this case, toFlow has to check if Publisher is the bridge's own type, look into it and extract the original flow. This is not available with the current lambda form. Since both wrappings are really thin, it doesn't really matter if one goes instanceof + cast or let the JIT inline the calls.

**Comment by viktorklang** [comment]
Does the HotSpot JIT inline N-level nestings? And how would it trace this
when you pass the instance around?

On Sat, Nov 14, 2015 at 3:54 PM, David Karnok <notifications@github.com>
wrote:

> In this case, toFlow has to check if Publisher is the bridge's own type,
> look into it and extract the original flow. This is not available with the
> current lambda form. Since both wrappings are really thin, it doesn't
> really matter if one goes instanceof + cast or let the JIT inline the calls.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/reactive-streams/reactive-streams-jvm/issues/294#issuecomment-156708880>
> .
>



-- 
Cheers,
√

**Comment by akarnokd** [comment]
By default, HS inlines something like 20 levels deep as far as I remember but this can be increased with command line parameters. But why would you want to have such pass-through wrap-unwrap in a codebase? I think the dev should recognize this as being unnecessary and simply not do it.

**Comment by viktorklang** [comment]
Having written a couple of these converters in the past, you'll be amazed
how people use them. Having things end up like a N-level nested data
structure which could be prevented with a simple branch is a cheap price to
pay in order to avoid some pretty weird error reports. :)

On Sat, Nov 14, 2015 at 8:27 PM, David Karnok <notifications@github.com>
wrote:

> By default, HS inlines something like 20 levels deep as far as I remember
> but this can be increased with command line parameters. But why would you
> want to have such pass-through wrap-unwrap in a codebase? I think the dev
> should recognize this as being unnecessary and simply not do it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/reactive-streams/reactive-streams-jvm/issues/294#issuecomment-156738411>
> .
>



-- 
Cheers,
√

**Comment by hepin1989** [comment]
@akarnokd It is needed,as you can take a look at the ForkJoinPool 's code.

**Comment by akarnokd** [comment]
Fine, I've updated the bridge to do the checks, casts and unwrapping if necessary.

**Comment by viktorklang** [comment]
@akarnokd Excellent! Thank you

**Comment by viktorklang** [comment]
@akarnokd Would you like to contribute it to reactive-streams-jvm?

**Comment by akarnokd** [comment]
Sure.

**Comment by viktorklang** [comment]
Fantastic! Would you mind opening a PR?

**Comment by akarnokd** [comment]
I know very little about Gradle, subprojects or how to setup a JDK 9 environment.

**Comment by viktorklang** [comment]
Same here, but having a PR means that more people can help out.
Collaborating via Gists is slightly less fun :)

On Sat, Nov 21, 2015 at 10:15 PM, David Karnok <notifications@github.com>
wrote:

> I know very little about Gradle, subprojects or how to setup a JDK 9
> environment.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/reactive-streams/reactive-streams-jvm/issues/294#issuecomment-158681763>
> .
>



-- 
Cheers,
√

**Comment by rotilho** [comment]
I think a easier and more reliable would be create another jar for java 9 which will extend the org.reactivestreams.* interfaces to their equivalent java.util.concurrent.Flow.*

I can create a PR with this change if you agree.

**Comment by akarnokd** [comment]
There is [already a bridge PR](https://github.com/reactive-streams/reactive-streams-jvm/pull/296) waiting for Java 9/Travis/Gradle to be operational.

Also implementing both interfaces at the same time causes ambiguities, plus requires internal bridging if you don't want to duplicate logic.

```java
interface MixPublisher<T> extends 
org.reactivestreams.Publisher<T>, java.util.concurrent.Flow.Publisher<T> { }

interface MixSubscriber<T> extends
org.reactivestreams.Subscriber<T>, java.util.concurrent.Flow.Subscriber<T> { }

MixPublisher<T> p = ...
MixSubscriber<T> s = ...

p.subscribe(s);
 ^               
  ambiguous overload
```

**Comment by rotilho** [comment]
I already took a look however add the bridge IMO will make things more complicate. My idea is make the reactive-streams exchange the java9 classes, like

interface Publisher<T> extends Flow.Publisher<T> {}

and release a new module with org.reactivestreams:reactive-streams-java9

In this way we are not going to have ambiguities and it will allow all current implementation compatible with java 9 if running in java 9 environment.

The downside it will be the dependency management.

**Comment by viktorklang** [comment]
@rotilho That solution will not fly: jigsaw will choke on it and it will create classpath-order issues.

**Comment by viktorklang** [comment]
Awesome to be able to close this issue, @akarnokd! :)
