### ISSUE TITLE
request(n) vs on/off for flow control

### ISSUE THREAD

**Issue by maxwindiff** [reactive-streams/reactive-streams-jvm#295]
Reactive-streams uses request(n) as the flow control mechanism. I'm wondering if any alternate flow control mechanisms have been considered before. One idea I'm thinking of is a switch on / switch off model:

```java
public interface Subscription {
  // Starts emitting elements. The publisher can emit as many elements as
  // it want until switchOff() is called.
  void switchOn();

  // Halts emitting elements. The publisher should eventually stop emitting
  // elements. The subscriber can call switchOn() to resume.
  void switchOff();

  // Same semantics as the existing cancel()
  void cancel();
}

// the Publisher/Subscriber/Processor interfaces are unchanged
```

This model has two main advantages:

1. When the subscriber is operating at the same or higher speed as the producer, there is no need to do any `request()` calls, which may improve throughput.
2. When a processor needs to translate between input and output types, it doesn't have to convert / estimate the request count. One example is a processor that receives `ByteBuffers`, decode them to UTF-8 strings, and emits each line as a `String`.

On the other hand there seem to be some obvious disadvantages:

1. `switchOff()` is inherently racy in the sense that publishers can't practically guarantee the subscriber will not receive elements after `switchOff()` is called, so flow control is less "strict". Even if publishers try their best to honor `switchOff()`, "leftover elements" can still be a problem in longer processing pipelines. By pipeline I mean means a series of processors connected together.
2. It's not obvious how to implement certain types of publishers, the simplest example being a publisher that emits elements generated from a generator function. If it just keeps emitting elements in `switchOn()`, the subscriber may never get a chance to call `switchOff()`. In general `switchOn()` provides less information than `request(n)` so publishers are more restricted.

I'm not proposing changing anything here (obviously). I'm mostly curious if something like this have been considered before and whether the advantages / disadvantages above are well founded.

**Comment by drewhk** [comment]
The disadvantages are exactly what you enumerated.

 > When the subscriber is operating at the same or higher speed as the producer, there is no need to do any request() calls, which may improve throughput.

If you use larger request counts then the cost of these requests are amortized. 

> When a processor needs to translate between input and output types, it doesn't have to convert / estimate the request count. One example is a processor that receives ByteBuffers, decode them to UTF-8 strings, and emits each line as a String.

You don't need to, actually. What Akka Streams does is that evers processing stage maintains a buffer, and processing logics do not call request, instead they consume elements from this buffer directly. Once buffer occupancy drops below a threshold, the framework in the background automatically requests the next batch. This approach turned for us to be the only one that properly composes and works, especially in the presence of cycles and fairness requirements.

**Comment by akarnokd** [comment]
Same thing happens with RxJava, although few of the algorithms use thresholding and just request(1) once one element is consumed. The pattern requires you to maintain a counter of elements so you can start and stop the upstream in case of an async boundary in addition ot a reqular queue:

```java
long count;
public void onNext(T value) {
   queue.offer(value);
   if (++count == max) {
      subscription.switchOff();
   }
}

void drainOnAnotherThread() {
    T q = queue.poll();
    if (q != null) {
        if (--count <= threshold) {
           subscription.switchOn();
        }
    }
}
```

Here, you now have a race on the `count` variable which has to be turned into an `AtomicLong` at least at which point you essentially ended up with the same structures as they are now: switchOff is no-op and switchOn() is just request(prefetchAmount).

**Comment by maxwindiff** [comment]
@drewhk Thanks, that's a great pointer. Do you know was there any discussion on the cycles / fairness / composability concerns I can read more about?

@akarnokd You are quite right. A user of the switchOn/switchOff mechanism will probably use some sort of low water mark / high water mark, which can be effectively simulated with the approach @drewhk mentioned. (By the way I just came across your blog series on RxJava internals. It's very illuminating!)

**Comment by drewhk** [comment]
> Do you know was there any discussion on the cycles / fairness / composability concerns I can read more about?

Not that I know of. We have some internal documents about our design decisions but these have been not yet compiled into a public consumable format. I plan to write up these after 2.0. Although if you are interested in the more theoretic background then Petri net theory covers most of the results that are applicable to bounded streaming (more specifially, well formed, free choice Petri nets). This is my favorite on this topic: https://www7.in.tum.de/~esparza/bookfc.html (available freely)

**Comment by maxwindiff** [comment]
@drewhk That's so unexpected and awesome, thanks!

**Comment by viktorklang** [comment]
Hi Max,

we had a lot (many many many) of discussions before we settled on the
existing solution.

The interfaces and spec of Reactive Streams are best thought of as
distributed entities where all method invocations are message sends. With
that in mind it is not feasible to employ Nak:ing since there can be
message loss.

----
Cheers,
√

**Comment by maxwindiff** [comment]
@viktorklang Thanks for explaining this perspective also.

I think I've got the answers thanks to everyone. Closing this issue.

**Comment by viktorklang** [comment]
Thanks for the great question, Max!

-- 
Cheers,
√
