### ISSUE TITLE
Examples v. implementations

### ISSUE THREAD

**Issue by evacchi** [reactive-streams/reactive-streams-jvm#299]
Is it okay / does it make sense to depend *on* the provided examples to scrap some boilerplate from an otherwise very straightforward implementation ? e.g., can I feed my own `Iterator` to `AsyncIterablePublisher` and extend `AsyncSubscriber` ? Should I depend on it via maven dependency or am I supposed to duplicate the code in my own repository ?

Thanks in advance.

**Comment by akarnokd** [comment]
Reactive-Streams is hard to implement properly. I wouldn't depend on the examples and I suggest you look/wait for a proper library. Unfortunately, all libraries that I know of have either too early RS support (with bugs and performance deficiencies). 

Probably the closest thing to a reliable release is Project Reactor 2.5 right now. There is, of course, RxJava 2.0 preview which kind of stuck due to admin problems (of which I have my own fork `com.github.akarnokd:rxjava2-backport:2.0.0-RC2` that I tend to roll forward).

**Comment by viktorklang** [comment]
I suspect @akarnokd is a tad more pessimistic than I am here :). If I were you and I only needed what's provided by the examples, I'd copy the code verbatim and put it on my own package (the examples are in the public domain), and make sure I run the TCK against the implementations.

Reactor and RxJava 2.0 aside, there's also Akka Streams which is approaching its first non-experimental, fully-supported release (current version is 2.4.2-RC1: http://akka.io/news/2016/01/26/akka-2.4.2-RC1-released.html).

**Comment by evacchi** [comment]
@viktorklang that was exactly how I intended to proceed; code is almost verbatim, except that I've thought I would make it package-private, since it is purely an implementation detail that might change. My implementation has been run against the TCK.

@akarnokd my intentions were to provide a connector to a third-party data source using RS so that it would be framework-agnostic. I was not aware of the RxJava 2.0 problems, although I did see that they are yet to make a stable release. Are you able to share more details? I did ask on their Gitter channel an ETA for 2.0 release, but they did not reply. Thanks!

**Comment by viktorklang** [comment]
@evacchi Since you won't even "leak" the implementation I think your decision is the right way forward. Have fun with Reactive Streams! :)

**Comment by akarnokd** [comment]
RxJava 2.0 preview is technically functioning (and all discovered issues have a PR for it), verified by 3700+ unit tests. I don't really get feedback either and I have only speculations about what's going on behind the scenes. Practically, I'm maintaining RxJava, respond to questions and bug reports but have limited rights. (Things didn't stop in the reactive world and I consider 2.0, in its current form, an outdated library.) Frankly, I don't expect RxJava 2.0 being released anytime soon.

I'm don't know how you'd want to expose the `Publisher` in your case, but if you want to do it via a method, then consider adding an overload that takes a lambda of the following form:

```java
<T, U extends Publisher<T>> U toPublisher(Function<Publisher<T>, U>);
```

which allows a fluent conversion to be applied in-sequece:

```java
yourSource.toPublisher(Observable::wrap).map(...).filter(...)
```

instead of

```java
Observable.wrap(yourSource.toPublisher()).map(...).filter(...)
```

**Comment by evacchi** [comment]
@viktorklang I have just made public https://github.com/unicredit/kafka-reactive-streams ; it passes all the mandatory tests in TCK via reactive-streams examples (except the stderr output in issue #300). You might want to consider adding it to the [list of available implementations](http://www.reactive-streams.org/announce-1.0.0) or maybe consider it for addition in 1.0.1 :-)

@akarnokd Thanks for your very useful feedback! If you please, we can continue discussing any issues regarding this library on its own repository.

**Comment by akarnokd** [comment]
Sure. Isn't #300 indicating that you have a real problem where onComplete fires before onSubscribe?

**Comment by evacchi** [comment]
I'm not sure. I believe in this case it is actually the mock publisher who is misbehaving

**Comment by viktorklang** [comment]
@evacchi Yes, this is what I am suspecting too, (i.e. a bug in the TCK)

**Comment by rstoyanchev** [comment]
I think @akarnokd is quite right especially from the perspective of a library vs an application. The [RxJava wiki](https://github.com/ReactiveX/RxJava/wiki/Reactive-Streams#recommended-approach) recommends that libraries expose Reactive Streams in their API and leave the choice of a composition library to the application which is sound advice but in practice very often libraries need to compose logic internally too and once you do exposing it in your API vs a basic `Publisher` makes sense. It allows other 3rd party libraries for example to compose logic on top while remaining agnostic to the composition library of choice for the application. This is exactly what Ratpack has done and for a good reason.

There is certainly a need for a Reactive Streams library focused on essential infrastructure around Reactive Streams that libraries can use without re-inventing the wheel. That's the goal for [Reactive Streams Commons](https://github.com/reactor/reactive-streams-commons).

**Comment by alkemist** [comment]
@akarnokd …

> Unfortunately, all libraries that I know of have either too early RS support (with bugs and performance deficiencies).

Ratpack certainly falls into that category. If you have any advice/suggestions, they'd be greatly appreciated.

**Comment by smaldini** [comment]
@alkemist The working solution so far for reactor is to just fully cooperate and integrate with the RSC research project and hopefully release that soonish in two flavors : light reactor-core, 400kb, common operations fully based on RSC [Flux](http://next.projectreactor.io/core/docs/api/reactor/core/publisher/Flux.html) and [Mono](http://next.projectreactor.io/core/docs/api/reactor/core/publisher/Mono.html) and full scope reactor-stream . From my point of view, RS

**Comment by alkemist** [comment]
@smaldini I'm not entirely sure what you are proposing/suggesting. I'm also not sure what the “RSC research project” is.

**Comment by evacchi** [comment]
@alkemist I guess RSC stands [Reactive Streams Commons](for https://github.com/reactor/reactive-streams-commons) linked in @rstoyanchev [comment](#issuecomment-178289749)

**Comment by smaldini** [comment]
Sorry @alkemist edited with the link.

**Comment by alkemist** [comment]
Thanks @smaldini

**Comment by viktorklang** [comment]
Can we close this?

**Comment by evacchi** [comment]
think so. thanks.
