### ISSUE TITLE
example.unicast.AsyncSubscriberTest prints to stderr violation of rule #1.09

### ISSUE THREAD

**Issue by evacchi** [reactive-streams/reactive-streams-jvm#300]
org.reactivestreams.tck.SubscriberBlackboxVerification#required_spec210_blackbox_mustBePreparedToReceiveAnOnErrorSignalWithPrecedingRequestCall prints to stderr:

```
java.lang.IllegalStateException: Publisher violated the Reactive Streams rule 1.09 signalling onComplete prior to onSubscribe.
	at org.reactivestreams.example.unicast.AsyncSubscriber.handleOnComplete(AsyncSubscriber.java:136)
	at org.reactivestreams.example.unicast.AsyncSubscriber.run(AsyncSubscriber.java:203)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by viktorklang** [comment]
@evacchi Steps to reproduce?

./gradlew clean check

passes on both reactive-streams master and on v1.0.0 here

**Comment by evacchi** [comment]
I came across this while testing my own implementation in the IDE. Gradle actually swallows stderr by default, but you can see the error in the report `examples/build/reports/tests/classes/org.reactivestreams.example.unicast.AsyncSubscriberTest.html` and clicking "Standard error":

![screenshot](http://i.imgur.com/EZt5Nrz.png)

The output comes from line 136 in `AsyncSubscriber.java`:

```java
  // Here it is important that we do not violate 2.2 and 2.3 by calling methods on the `Subscription` or `Publisher`
  private void handleOnComplete() {
    if (subscription == null) { // Technically this check is not needed, since we are expecting Publishers to conform to the spec
      // Publisher is not allowed to signal onComplete before onSubscribe according to rule 1.09
      (new IllegalStateException("Publisher violated the Reactive Streams rule 1.09 signalling onComplete prior to onSubscribe.")).printStackTrace(System.err);
    } else {
      done = true; // Obey rule 2.4
      whenComplete();
    }
  }
```

**Comment by viktorklang** [comment]
I'll have to have a look. What kind of build tool swallows stderr by
default?!

Thanks for opening the issue, we should release a 1.0.1 release at some
point anyway and if this indeed is a bug then it would be a good candidate
for that release.

-- 
Cheers,
√

**Comment by alkemist** [comment]
>  What kind of build tool swallows stderr by
default?!

It doesn't swallow it. It's there in the test reports. It's just not forwarded to the console by default.

**Comment by viktorklang** [comment]
I run all test from terminal so it is unfortunate that it is silently
removed from console output :-/

-- 
Cheers,
√

**Comment by alkemist** [comment]
Sure, it's a matter of taste.

Do you want the output to be sent to the console for the RS build?

**Comment by viktorklang** [comment]
I think that would be nice, is that something you could arrange?

-- 
Cheers,
√

**Comment by viktorklang** [comment]
@evacchi I can't seem to reproduce (no stderr output in the report)

**Comment by evacchi** [comment]
@viktorklang will check and get back to you

**Comment by viktorklang** [comment]
@evacchi Ping

**Comment by evacchi** [comment]
looks clean now.
