### ISSUE TITLE
Typo in three places

### ISSUE THREAD

**Issue by akauppi** [reactive-streams/reactive-streams-jvm#304]
https://github.com/reactive-streams/reactive-streams-jvm/search?utf8=%E2%9C%93&q=Compuatation

Noticed this when running reactive-kafka tests.

**Comment by viktorklang** [comment]
Thanks for the heads up!

I'm internally debating whether it would be fine to change this in a dot-release or not. It won't be binary compatible, but otoh it is for test code. Wdyt?
