### ISSUE TITLE
Separate TCK timeouts for things to happen from things to not happen

### ISSUE THREAD

**Issue by jroper** [reactive-streams/reactive-streams-jvm#308]
The TCK has one timeout that's used for two purpose, it's used as a limit to wait for things to happen, eg assert that a signal was eventually received, and it's used to wait for things to never happen, eg assert that a signal is never received.  The default value is 500ms, and using this timeout the TCK may take, for example, around 20 seconds to run.  Now on most laptops, 500ms is reasonable for both values, the tests don't take too long as a result of waiting for things not to happen, and things almost always happen within 500ms.

However, on CI servers, it's a different story.  Take for example Travis.  Our experience with running Play on Travis shows that timeouts need to be as long as 10 seconds, since travis uses a container architecture that runs many builds on the one server concurrently, and GC pauses can take seconds.  But if you change the timeouts to 10 seconds, then the build can end up taking many minutes, because now it's waiting 10 seconds every time it wants to assert that something doesn't happen.

I think these two timeouts should be separated so they can be individually configured.

**Comment by drewhk** [comment]
Where is that `+1` button when you need it :)

**Comment by drewhk** [comment]
Ah found it ;)

**Comment by ktoso** [comment]
Yeah, good idea :+1:

**Comment by viktorklang** [comment]
Sounds great, and should even be possible to implement in a backwards-compatible way.
PRs would be very welcome!

**Comment by ktoso** [comment]
Sure, why not, and it's compatible too AFAICS.
