### ISSUE TITLE
FluxDispatchOn interrupts thread before calling onComplete or onError

### ISSUE THREAD

**Issue by sskrla** [reactive-streams/reactive-streams-jvm#310]
When using `.dispatchOn` Flux calls `.interrupt()` on the current thread (via `scheduler.accept(null)`) before it calls the `onError` or `onComplete`.

Specifically, this caused issues using the ElasticSearch client as it throws an exception if the current thread is an interrupted state when you make a blocking API call.

For example:

```
Fluxion.from(documents)
    .dispatchOn(processorsExecutorService)
    .buffer(batchSize)
    .onNext( requests -> {
        BulkRequestBuilder builder = client.prepareBulk();
        requests.forEach(builder::add);
        builder.get() // Throws interrupted exception on last batch
    })
    .subscribe()
```

**Comment by akarnokd** [comment]
Wrong repo...

**Comment by smaldini** [comment]
Moved to reactor/reactor-core.
