### ISSUE TITLE
Dangling footnote in Publisher section

### ISSUE THREAD

**Issue by anthonyvdotbe** [reactive-streams/reactive-streams-jvm#316]
The [Publisher section](https://github.com/reactive-streams/reactive-streams-jvm/blob/master/README.md#1-publisher-code) of the specification contains a dangling footnote. I believe it should be integrated in rule 1.9 as "for all other situations [1] the only legal way".

**Comment by ktoso** [comment]
I agree, I checked when the footnote was introduced and [it originally was](https://github.com/reactive-streams/reactive-streams-jvm/commit/c66aa6b3cd9334dc0ef6d7c002ceeaed21075909#diff-04c6e90faac2675aa89e2176d2eec7d8R90) about 1.12 (which is gone now) but in a similar context like 1.9 explains nowadays, would you like to submit the fix or shall I?
