### ISSUE TITLE
Asynchronous vs Synchronous Processing: reword "push-based stream"

### ISSUE THREAD

**Issue by anthonyvdotbe** [reactive-streams/reactive-streams-jvm#326]
The section [Asynchronous vs Synchronous Processing](https://github.com/reactive-streams/reactive-streams-jvm#asynchronous-vs-synchronous-processing) contains the following phrase:
> [...] push-based stream.

I was confused to see the term "push-based" here, expecting to see pull-based instead. Even though @akarnokd clearly [explained](https://github.com/reactive-streams/reactive-streams-jvm/issues/177#issuecomment-207603260) explained why this makes sense, I believe it would be useful to slightly reword this. @viktorklang [proposed](https://github.com/reactive-streams/reactive-streams-jvm/issues/177#issuecomment-208214078) `dynamic push-pull stream`. Another idea I had is `request/push-response stream`.

**Comment by viktorklang** [comment]
This seems like a "no-brainer" to me. :+1: (I of course vote for my own proposal ;))
