### ISSUE TITLE
Source files without license headers

### ISSUE THREAD

**Issue by puntogil** [reactive-streams/reactive-streams-jvm#333]
Hi

All java source files are without license headers.

Please, confirm the licensing of code and/or content/s, and add license headers

https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Clarification

Thanks in advance

Regards

**Comment by viktorklang** [comment]
Hi,

we can most definitely add license headers,
in the mean time, the entire project is under CC0: https://github.com/reactive-streams/reactive-streams-jvm/blob/master/LICENSE

**Comment by alkemist** [comment]
There are two common approaches to enforcing license headers in Gradle builds. 

1. Using Checkstyle and a rule to check for a pattern at the start of files
2. https://github.com/hierynomus/license-gradle-plugin

(2) has the benefit of being able to rectify missing headers.

@viktorklang if you want me to wire this in I'm willing. That said, we aren't talking about a lot of source so doing this one-time by hand and manual enforcement for subsequent changes is viable.

**Comment by viktorklang** [comment]
@alkemist I think you're right: one-time manual "enforcement" seems like the most efficient expenditure of time (since we aren't anticipating adding file at this point). I'd love it if you could add the headers. Thank you.

**Comment by puntogil** [comment]
Seem license header are still not available in these folder: api, tck

**Comment by ktoso** [comment]
It is in the root of the entire repo, I don't usually see projects put license in all subfolders.
I think it's clear that the license is in there and applies to all projects.

**Comment by ktoso** [comment]
Followed up in https://github.com/reactive-streams/reactive-streams-jvm/pull/344
