### ISSUE TITLE
Doesn't Rule 3.13 contradict 1.10?

### ISSUE THREAD

**Issue by schauder** [reactive-streams/reactive-streams-jvm#334]
3.13 says:

> Re-subscribing with the same Subscriber object is discouraged [see 2.12], but this specification **does not mandate that it is disallowed** since that would mean having to store previously cancelled subscriptions indefinitely.

1.10 says:

> Publisher.subscribe MAY be called as many times as wanted but **MUST be with a different Subscriber each time**

wouldn't the discouraged part of 3.13 result in a violation of 1.10 and thereby it is not just discouraged, but actually disallowed?

Or missing something?

**Comment by rkuhn** [comment]
1.10 defines permissible behavior of callers of `subscribe`, i.e. whoever calls that method must make sure to use a fresh `Subscriber` every time.

3.13 mandates that the `Publisher` drops all references to a `Subscriber` after the associated `Subscription` has been cancelled, meaning that the `Publisher` cannot be held responsible for enforcing that 1.10 is obeyed.

Hence, there is no contradiction, it is just that different parties are held accountable for different parts of the contract.

**Comment by schauder** [comment]
Thanks, that makes sense. Would be great to have this kind of stuff in some comments to the rules. But I think there is already an issue for that, right?

**Comment by viktorklang** [comment]
Yeah, I should get to that at some point. :S 
I should try to set aside a week for that. If possible.

**Comment by viktorklang** [comment]
Perhaps start an FAQ in the mean time?
Could someone try to do that?

**Comment by viktorklang** [comment]
AFAIK solved by #339
