### ISSUE TITLE
There is a footnote in section 1 but nothing refers to that footnote

### ISSUE THREAD

**Issue by schauder** [reactive-streams/reactive-streams-jvm#335]
The footnote I'm talking about is 

> [1] : A stateful Publisher can be overwhelmed, bounded by a finite number of underlying resources, exhausted, shut-down or in a failed state.

**Comment by viktorklang** [comment]
The link is in 1:9:

9	Publisher.subscribe MUST call onSubscribe on the provided Subscriber prior to any other signals to that Subscriber and MUST return normally, except when the provided Subscriber is null in which case it MUST throw a java.lang.NullPointerException to the caller, for all other situations [1] the only legal way to signal failure (or reject the Subscriber) is by calling onError (after calling onSubscribe).
