### ISSUE TITLE
Artifact shouldn't use a postfix in the version number in Export-Package

### ISSUE THREAD

**Issue by KMax** [reactive-streams/reactive-streams-jvm#349]
This is related to the OSGi packaging of the artifact #158.

Just tried to use `reactive-streams:1.0.0` package from [Maven Central](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.reactivestreams%22%20AND%20a%3A%22reactive-streams%22) with Apache Felix. Since `io.reactivex.rxjava2:rxjava` depends on it.

Apache Felix successfully bound `reactive-streams` to `rxjava` only after I remove `.release` from `Export-Package: org.reactivestreams;version=1.0.0.release` in `MANIFEST.MF`

**Comment by ktoso** [comment]
Looks like a bug to me, thanks for reporting.

That `.release` was added here https://github.com/reactive-streams/reactive-streams-jvm/commit/810adfe4678ac6522b4fec8a5f56c802f7597a98 
And was a follow up to the "wrong published version (1.0.0.final)" which also broke osgi.

Perhaps @smaldini has had a reason to include the `.release` suffix when releasing? Please chime in. Seems rather off, I've never seen this difference between actual version and the one in the manifest anywhere be made on purpose.

For reference, the manifest in `1.0.0` is currently:

```
Manifest-Version: 1.0
Bundle-Description: Reactive Streams API
Export-Package: org.reactivestreams;version="1.0.0.release"
Bundle-SymbolicName: org.reactivestreams.reactive-streams
Bundle-Version: 1.0.0.release
Bundle-Name: reactive-streams
Bundle-ManifestVersion: 2
Bnd-LastModified: 1424093440000
Bundle-Vendor: Reactive Streams SIG
Bundle-DocURL: http://reactive-streams.org
Created-By: 1.8.0_31 (Oracle Corporation)
Tool: Bnd-2.1.0.20130426-122213
```

We should and can fix it in the 1.0.1 patch release which would clean up such things.
