### ISSUE TITLE
Improve NOP term definition

### ISSUE THREAD

**Issue by artem-zinnatullin** [reactive-streams/reactive-streams-jvm#361]
Current definition:

>NOP: Execution that has no detectable effect to the **calling thread**, and can as such safely be called any number of times.

`caller` would probably be better than `calling thread`. Thread is not what important for NOP.

So proposal is to change definition to:

>NOP: Execution that has no detectable effect for the caller, and can as such safely be called any number of times.

I'll create a PR if this change will be approved.

**Comment by viktorklang** [comment]
@artem-zinnatullin Hi Artem, thanks for starting this conversation!

I'm not sure I understand what the pros/cons would be for this change, would you mind elaborating on the drawbacks of the current formulation?

**Comment by artem-zinnatullin** [comment]
Sure, 

Main drawback I see is that most of the specification uses term **caller** to talk about return value or thrown exceptions, for instance:

>Return normally: Only ever returns a value of the declared type to the **caller**. The only legal way to signal failure to a Subscriber is via the onError method.

>MUST throw a java.lang.NullPointerException to the **caller**

>is to have **callers** of subscribe()

**calling thread** on the other hand is mostly used when specification talks about synchronous execution and non-obstructing implementations of functions:

>and should be as quick to execute as possible on the **calling thread**

>i.e. Publishers who execute their logic on the **calling thread**

**Comment by viktorklang** [comment]
@artem-zinnatullin Hi Artem,
the definition of NOP addresses runtime behavior on the calling thread. I guess one could write "caller / calling thread" in the definition instead but I am unsure if that makes things even clearer?

**Comment by artem-zinnatullin** [comment]
I think it does, but since I can't explain it better than I did already I'm closing the issue, it's not that important in the end :)
