### ISSUE TITLE
Create RELEASE-NOTES for 1.0.1

### ISSUE THREAD

**Issue by viktorklang** [reactive-streams/reactive-streams-jvm#363]
https://github.com/reactive-streams/reactive-streams-jvm/blob/master/RELEASE-NOTES.md

Including:

PublisherVerification:
-  public void untested_spec305_cancelMustNotSynchronouslyPerformHeavyCompuatation() throws Exception {
 +  public void untested_spec305_cancelMustNotSynchronouslyPerformHeavyComputation() throws Exception {

**Comment by seratch** [comment]
Is the release date decided?

**Comment by viktorklang** [comment]
@seratch Not 100%—I'd like to get  it out before end of June. I think we could do that, there's a bit of PR reviews / merging / testing to be had first tho.

**Comment by ktoso** [comment]
This can be closed I think? https://github.com/reactive-streams/reactive-streams-jvm/issues/363

**Comment by viktorklang** [comment]
@ktoso Aye.
