### ISSUE TITLE
quite confuse about how to use

### ISSUE THREAD

**Issue by oswaldl** [reactive-streams/reactive-streams-jvm#380]
any testcase or main method?

**Comment by akarnokd** [comment]
The Reactive-Streams specification targets library developers, not end-users directly, plus since it is itself a library, there is no main method to run.

**Comment by viktorklang** [comment]
@oswaldl Adding to what David said, you can find example implementations [here](https://github.com/reactive-streams/reactive-streams-jvm/tree/master/examples/src/main/java/org/reactivestreams/example/unicast) and examples on how to use the TCK to validate implementations [here](https://github.com/reactive-streams/reactive-streams-jvm/tree/master/examples/src/test/java/org/reactivestreams/example/unicast)
