### ISSUE TITLE
TCK: Provide test classes working directly on JDK9 interfaces

### ISSUE THREAD

**Issue by ktoso** [reactive-streams/reactive-streams-jvm#388]
There's two ways to go about this I guess:

Proposed style of rolling it out:

- change TCK code to work on JDK9 interfaces directly
- make current Verification classes go through adapters provided via https://github.com/reactive-streams/reactive-streams-jvm/issues/294
- add new Verification classes (named like "**FlowPublisher**...Verification" etc, which new users can use then

This would move "us" to test the JDK things directly, which is the end goal and allow slowly moving away from having to use the adapters for most impls (as impls move to implementing the JDK interfaces)

**Comment by viktorklang** [comment]
@ktoso I believe you wanted to take a stab at this? :)

**Comment by ktoso** [comment]
Yes, absolutely - work in progress already.
Terribly jet-lagged though, hope a good nights sleep today will get me hacking on to finish this up on monday US time.

**Comment by viktorklang** [comment]
Awesome. Let me know how I can help.

-- 
Cheers,
√

**Comment by akarnokd** [comment]
This should be simply a copy-paste of the current TCK in a new module and replacing `org.reactivestreams` with `java.util.concurrent.Flow`, right?

**Comment by ktoso** [comment]
That would not be nice for maintenance though ;)

**Comment by akarnokd** [comment]
I'm not a Gradle guru but I'm sure it can be automatically synchronized via a scripting.

**Comment by akarnokd** [comment]
> I'm not a Gradle guru but I'm sure it can be automatically synchronized via scripting.

Nope, it's still tedious as the references have to be carefully replaced since the containing package is `org.reactivestreams` too.
