### ISSUE TITLE
Bindings for Apple's Swift Language

### ISSUE THREAD

**Issue by hlovatt** [reactive-streams/reactive-streams-jvm#391]
Hi,

Has any work been done on Reactive Streams for Apple's Swift Language?

I have started an implementation: https://github.com/hlovatt/Concurrency-Utilities. One of the issues I came up with is what should the protocols be? 

I choose:

```
public protocol Processor: Subscriber, Publisher {}

public protocol Publisher {
    associatedtype PublisherT
    func subscribe<S>(_ subscriber: S) where S: Subscriber, S.SubscriberT == PublisherT
}

public protocol Subscriber {
    associatedtype SubscriberT
    func onComplete()
    func on(error: Error)
    func on(next: SubscriberT)
    func on(subscribe: Subscription)
}

public protocol Subscription {
    func cancel()
    func request(_ n: Int)
}
```

However, maybe someone else has already done some work in Swift.

**Comment by akarnokd** [comment]
I did only a [small experiment](https://github.com/akarnokd/akarnokd-misc-swift/blob/master/SwiftExperiments/ReactiveStreams.swift) myself, but I find Swift too alien compared to Java and its generics, and I couldn't express certain functional patterns.

**Comment by hlovatt** [comment]
@akarnokd,

Your interface is very similar to mine, which is encouraging.

What was the functional area you had a problem with? 

It would be interesting to see the problem as a test of whether this sort of interface in Swift is viable.

**Comment by akarnokd** [comment]
I can't remember exactly; I think it was something around co- and contra-variance in function callbacks and the rejection of casting up or down.

**Comment by hlovatt** [comment]
OK I think that is a valid point and a Swift Reactive Stream interface
should therefore also have at least:

public class AnySubscriber<T>: Subscriber {
    public typealias SubscriberT = T


    private let complete: () -> Void


    private let error: (Error) -> Void


    private let next: (T) -> Void


    private let subscribe: (Subscription) -> Void


    /// Wrap the given subscriber, which can be any type of subscriber, so
that the type becomes `AnySubscriber` regardless of the originating
subscriber's specific type.
    /// - parameter subscriber: The subscriber to wrap.
    init<S>(_ subscriber: S) where S: Subscriber, S.SubscriberT == T {
        complete = {
            subscriber.onComplete()
        }
        error = {
            subscriber.on(error: $0)
        }
        next = {
            subscriber.on(next: $0)
        }
        subscribe = {
            subscriber.on(subscribe: $0)
        }
    }


    public func onComplete() {
        self.complete()
    }


    public func on(error: Error) {
        self.error(error)
    }


    public func on(next: T) {
        self.next(next)
    }


    public func on(subscribe: Subscription) {
        self.subscribe(subscribe)
    }
}


Which I have required. It might also need `AnyPublisher` and `AnyProducer`.

  -- Howard.

**Comment by viktorklang** [comment]
Hi @hlovatt,

Should we perhaps create a reactive-streams-swift repo?

**Comment by hlovatt** [comment]
@Victor,

Yes that is a good idea.

Suggest:


https://github.com/hlovatt/Concurrency-Utilities/blob/master/Concurrency%20Utilities/ReactiveStream.swift

As the starting point of the repo.

What do you think?

  -- Howard.

**Comment by viktorklang** [comment]
@hlovatt Apologies for the delayed response here, I added a seeded repo here: https://github.com/reactive-streams/reactive-streams-swift
