### ISSUE TITLE
Clarification request for Rule 1.10 (Intent)

### ISSUE THREAD

**Issue by pavelrappo** [reactive-streams/reactive-streams-jvm#403]
> The intent of this rule is to have callers of `subscribe` be aware that a generic Publisher and a generic Subscriber cannot be assumed to support being attached multiple times. Furthermore, it also mandates that the semantics of `subscribe` must be upheld no matter how many times it is called.

Does it make sense to mention `Subscriber` here given [rule 2.12](https://github.com/reactive-streams/reactive-streams-jvm#2.12)?

**Comment by viktorklang** [comment]
@pavelrappo Yes, this is because the rule needs to be upheld both from the Publisher side of things, as well as the Subscriber side of things. (symmetry)

**Comment by pavelrappo** [comment]
Might it be the case that the spec is missing a description of an entity that is in charge of calling `publisher.subscribe(subscriber)`?  It's just that in some cases `Publisher` or `Subscriber` may share this role along with their main duty. 

Think of a "plumber" that has all the subscribers and publishers and connects them to each other according to some rules only this plumber knows.

**Comment by viktorklang** [comment]
@pavelrappo Interesting observation. What would the spec look like if that perspective was put in place?

**Comment by pavelrappo** [comment]
@viktorklang I'll have to think about it more.

**Comment by pavelrappo** [comment]
One more question, now about the rule (not the intent). Thread-safety is mentioned for calls to `Subscriber`'s methods and for calls to`Subscription`'s methods. However, nothing has been said (at least explicitly) about the only method of `Publisher`. 

So the question is this: should thread-safety of `Publisher.subscribe` be defined?

**Comment by viktorklang** [comment]
@pavelrappo Interesting question. Is there a scenario which would be problematic from this perspective?

**Comment by viktorklang** [comment]
@pavelrappo Shall I close this?

**Comment by viktorklang** [comment]
@pavelrappo Ping

**Comment by viktorklang** [comment]
@pavelrappo Ping

**Comment by pavelrappo** [comment]
> Is there a scenario which would be problematic from this perspective?

I guess any scenario where a `Publisher` is not confined to a single thread is potentially problematic. Unless this `Publisher` is stateless or immutable or both (e.g. a failed or a completed `Publisher`).

**Comment by viktorklang** [comment]
If `subscribe` invocations are coupled, then the Publisher needs to perform any necessary coordination.

**Comment by pavelrappo** [comment]
@viktorklang , I'm okay with your explanation. Thanks for the discussion.

**Comment by viktorklang** [comment]
@pavelrappo Thanks Pavel! I really appreciate that you ask for clarification, thank you!
