### ISSUE TITLE
TCK Improvement: Throw meaningful error in white box subscriber verification when Probe.registerOnSubscribe isn't called

### ISSUE THREAD

**Issue by jroper** [reactive-streams/reactive-streams-jvm#416]
Currently, none of the the `SubscriberWhiteboxVerification` tests check whether `WhiteboxSubscriberProbe.registerOnSubscribe` is invoked before it starts trying to use the puppet supplied by that invocation. So, if it wasn't invoked, it just throws an NPE:

```
java.lang.NullPointerException
	at org.reactivestreams.tck.SubscriberWhiteboxVerification$1.run(SubscriberWhiteboxVerification.java:83)
	at org.reactivestreams.tck.SubscriberWhiteboxVerification.subscriberTest(SubscriberWhiteboxVerification.java:497)
	at org.reactivestreams.tck.SubscriberWhiteboxVerification.required_exerciseWhiteboxHappyPath(SubscriberWhiteboxVerification.java:80)
```

It would be nice if this was checked, and a meaningful error message (saying that `registerOnSubscribe` hasn't been invoked) was thrown.

**Comment by ktoso** [comment]
Sounds like a good improvement, are you giving it a shot or should I try to next week (won't be able this week)?

**Comment by jroper** [comment]
I'll take a look today.

**Comment by viktorklang** [comment]
@jroper If the promise hasn't been completed at the time of trying to use it, it *should* yield a test failure:

    public T value() {
      if (isCompleted()) {
        return _value;
      } else {
        env.flop("Cannot access promise value before completion");
        return null;
      }
    }

Perhaps that failure is hidden by an NPE? In which case, we might want to both flop AND throw?

**Comment by viktorklang** [comment]
@jroper are these tests running without `runDefaultInit`? https://github.com/reactive-streams/reactive-streams-jvm/blob/master/tck/src/main/java/org/reactivestreams/tck/SubscriberWhiteboxVerification.java#L541

**Comment by viktorklang** [comment]
@jroper I'm planning on issuing the 1.0.2-RC1 within 24h and would love to include this improvement as well. Will you have time to take a stab at it, or can provide a "failing test" someone could use to verify if it gets fixed? Thank you!

**Comment by viktorklang** [comment]
@jroper 6h to go

**Comment by akarnokd** [comment]
@viktorklang Do you want the fix for this included in RC1? If so, I can have a look and post a fix today.

**Comment by viktorklang** [comment]
@akarnokd That'd be very nice. If the fix is small then it should be quick to inorporate (in time for RC1)

**Comment by akarnokd** [comment]
The OP is not very detailed on how to trigger this failure so I have to figure that out too. Plus, "none of the the SubscriberWhiteboxVerification tests check" indicates all of them is affected and should be tested/modified.

**Comment by viktorklang** [comment]
Ideally the fix can be applied in one place, but let's see what it turns out to need.

**Comment by ktoso** [comment]
Please assign milestone @viktorklang ?

**Comment by viktorklang** [comment]
@ktoso Done!
