### ISSUE TITLE
Flow Adaptor

### ISSUE THREAD

**Issue by robertroeser** [reactive-streams/reactive-streams-jvm#420]
Is the flow adapter necessary? Why doesn't the RS streams interface extend the Java 9 interfaces and then you create a multi-jar to decide which implementation to use? I feel like making an adapter like this is what you'd do before you had multi-jars, and that Java 9 added multi-jars to solve problems like this.

**Comment by akarnokd** [comment]
It doesn't work. RS is by default targeting Java 6 so it can't extend a Java 9 interface. Second, if there was an extension, it would only work in one direction, i.e., a method consuming an RS interface couldn't consume a Flow interface. Third, you can't introduce new API with multi-jars, especially if they are in different packages.

**Comment by viktorklang** [comment]
@robertroeser Thanks for your question. I hope David answered it. Don't hesitate to follow up, I'll close this Issue in the mean time.
