### ISSUE TITLE
1.3 imprecise

### ISSUE THREAD

**Issue by davidmoten** [reactive-streams/reactive-streams-jvm#431]
I was asked for documentation about signals being published serially by a Publisher and looked at 1.3. Seems rather imprecise. It says:

>onSubscribe, onNext, onError and onComplete signaled to a Subscriber MUST be signaled in a thread-safe manner—and if performed by multiple threads—use external synchronization.

The vague bit to me is *signalled in a thread-safe manner*. I think we can be more precise, something like:

>signals (onSubscribe, onNext, onError and onComplete) must be signaled to a Subscriber serially. 

The comment box for 1.3 could then mention that 

>the signals may be sent from different threads but there must be happens-before relationships between the signals sent to a Subscriber.

**Comment by viktorklang** [comment]
Hi @davidmoten,

apologies for the late response.

Good point. Perhaps we should say "sequentially", and if performed by multiple threads, each signal must happen-before the other?

@reactive-streams/contributors Wdyt?

**Comment by viktorklang** [comment]
@davidmoten Perhaps we should add it to the explanation of 3:2? https://github.com/reactive-streams/reactive-streams-jvm#3.2

**Comment by artem-zinnatullin** [comment]
As @davidmoten suggested originally, "serially" (see [Serializability, wiki](https://en.wikipedia.org/wiki/Serializability)) is a quite common term in multithreading/concurrency literature (also present in RxJava sources) that means "without overlapping in time",

might be a bit better choice than "sequentially" :)

**Comment by viktorklang** [comment]
@davidmoten 

How about:

>onSubscribe, onNext, onError and onComplete signaled to a Subscriber MUST be signaled serially—and if performed by multiple threads—use external synchronization.

**Comment by vietj** [comment]
@viktorklang when you use the happens-before term, does it also apply to the state managed by these methods ?

**Comment by viktorklang** [comment]
@vietj That is managed by [2:11](https://github.com/reactive-streams/reactive-streams-jvm#2.11)

**Comment by davidmoten** [comment]
@viktorklang 
>onSubscribe, onNext, onError and onComplete signaled to a Subscriber MUST be signaled serially—and if performed by multiple threads—use external synchronization.

Yeah that helps. I think we can do better with the term *external synchronization* though. All contributors here understand this but a wider audience might be confused by it. When I google "external synchronization" all I see is clock synchronization for distributed systems.

**Comment by viktorklang** [comment]
@davidmoten Any suggestions there?

**Comment by davidmoten** [comment]
The best I can come up with is to use *happens-before* terminology. *happens-before* applies to actions not signals (messages) so mixing *happens-before* with the verb/noun signal is a tad confusing.

I notice that the glossary defines *signal* like so:

>As a noun: one of the onSubscribe, onNext, onComplete, onError, request(n) or cancel methods. As a verb: calling/invoking a signal.

AFAICS the normal interpretation of a noun *signal* in a computer science context is as a message and we have now redefined it to be the action incurred by that message. A tad confusing but we can run with it.

With regards to:

>onSubscribe, onNext, onError and onComplete signaled to a Subscriber MUST be signaled serially—and if performed by multiple threads—use external synchronization.

We don't need to add "and if performed by multiple threads ..." because it is redundant (the wording implies it is an extra criterion) but rather some clarification about the use of multiple threads is nice to have in the comment under the rule.

So I'm thinking:

>onSubscribe, onNext, onError and onComplete signaled to a Subscriber MUST be signaled serially.

and a comment of:

>*Serially* does not preclude the signalling of signals from multiple threads but it does demand that there be a *happens-before* relation between the signals.

**Comment by viktorklang** [comment]
@davidmoten "signal" is conceptually messages in this model, but since synchronous Publishers and Subscribers are permitted, it has to refer to the methods (as a noun).

>Serially does not preclude the signalling of signals from multiple threads but it does demand that there be a happens-before relation between the signals.

Sounds like a great explanation. I would want to avoid using "demand" in this context as to avoid confusion with the other notion of "demand" in this spec. Perhaps something like this?

*`Serially` does not preclude the signalling of signals from multiple threads but it does require establishing a happens-before relation between each of the signals.*

**Comment by davidmoten** [comment]
@viktorklang sounds good. Might be able to improve on my double negative:

*`Serially` allows the signalling of signals from multiple threads but it does require establishing a happens-before relation between each of the signals.*

Could be simplified a bit more? Perhaps

*`Serially` allows the signalling of signals from multiple threads but there must be a happens-before relation between each of the signals.*

**Comment by viktorklang** [comment]
@davidmoten Perhaps even simpler:

*`Serially` permits the signalling of signals from multiple threads if a happens-before relation between each of the signals is established.*

**Comment by davidmoten** [comment]
I'm good with that. Could replace the *is established* with *there is*:

*`Serially` permits the signalling of signals from multiple threads if there is a happens-before relation between each of the signals.*

**Comment by viktorklang** [comment]
@davidmoten I felt that wording to be a bit vague on what was required by the implementor. Is there some wording which clearly states that the implementor much provide this?

**Comment by davidmoten** [comment]
I understand. If you want to emphasize that then let's leave it as you had it.

**Comment by viktorklang** [comment]
@davidmoten Cool. Do you want to do the honors of opening a PR?

**Comment by davidmoten** [comment]
Okey doke

**Comment by davidmoten** [comment]
I realize there is a tad more to talk about. 

We propose for 1.3:

`onSubscribe`, `onNext`, `onError` and `onComplete` signaled to a `Subscriber` MUST be signaled serially.

and a comment of:

*`Serially` permits the signalling of signals from multiple threads if a happens-before relation between each of the signals is established.*

However, I see there is a convention in place where every comment starts with "The intent of this rule is". If we do follow the convention then perhaps something like:

*The intent of this rule is to permit the signalling of signals from multiple threads if a happens-before relation between each of the signals is established.*

**Comment by viktorklang** [comment]
@davidmoten Great catch with the Intent-section! I believe we also need to supersede the use of "External synchronization" in the spec (amend 2:7).

Come to think of it, I think we need an iff in the intent:

*The intent of this rule is to permit the signalling of signals from multiple threads iff a happens-before relation between each of the signals is established.*

**Comment by davidmoten** [comment]
>Come to think of it, I think we need an iff in the intent

Yeah I agree, you want it expanded (if and only if)?

To retire the "External synchronization" term we'll need to
* remove External Synchronization entry from glossary
* reword Thread-Safety in Glossary
* reword 2.7

I'll put up some suggestions and we can bounce them around.

**Comment by viktorklang** [comment]
@davidmoten I think we need to spell it out so people who are unfamiliar with it don't think it's a typo.

Your plan sounds good, I'm looking forward to having a look at your suggestions.

**Comment by viktorklang** [comment]
@davidmoten What's the status here, David?

**Comment by davidmoten** [comment]
@viktorklang I'll have another look this week

**Comment by davidmoten** [comment]
@viktorklang 
Thanks for working with me on this one. Apologies for the big delay. I'm still stretched a bit far to invest time in the retirement of the term "External Synchronization". I'd be happy to make a PR to cover the 1.3 rewording and raise an issue as a TODO on further rewording. Does that suit for the moment?

**Comment by viktorklang** [comment]
@davidmoten No worries, I understand. As for 2.7, see the discussion here: https://github.com/reactive-streams/reactive-streams-jvm/issues/405#issuecomment-414566683

**Comment by viktorklang** [comment]
@davidmoten Ping.

**Comment by viktorklang** [comment]
@davidmoten Ping.
