### ISSUE TITLE
Incorrect documentation for subscription.request

### ISSUE THREAD

**Issue by tferi-da** [reactive-streams/reactive-streams-jvm#440]
I believe [this line](https://github.com/reactive-streams/reactive-streams-jvm/blob/master/api/src/main/java/org/reactivestreams/Subscription.java#L26) is misleading.
According to rule 3.17 if demand exceeds Long.MAX_VALUE the publisher should keep working, and may become unbounded. There's even a [test](https://github.com/reactive-streams/reactive-streams-jvm/commit/a3005b779344bf8ed6047d73d89ad9b39bb1d1a7) which is checking that demand beyond Long.MAX_VALUE is tolerated without errors.

**Comment by viktorklang** [comment]
Hi @tferi-da,

Thanks for opening this issue!

I'm inclined to agree with your assessment,
what do you think about amending it as such:

     * It can be called however often and whenever needed—but if the outstanding cumulative demand ever becomes Long.MAX_VALUE or more, it may be treated by the {@link Publisher} as "effectively unbounded".

**Comment by tferi-da** [comment]
Yes @viktorklang, I think that's much better. Thank you for responding so quickly.

**Comment by viktorklang** [comment]
@reactive-streams/contributors Wdyt?

**Comment by viktorklang** [comment]
@reactive-streams/contributors Ping.

**Comment by tferi-da** [comment]
Thank you for the fix @viktorklang
