### ISSUE TITLE
Unmappable characters in the source

### ISSUE THREAD

**Issue by pavelrappo** [reactive-streams/reactive-streams-jvm#457]
I attempted to compile TCK sources manually and ran into multiple `javac` issues like the following:

`error: unmappable character (0xE2) for encoding US-ASCII`

It turns out reactive streams sources use a small number of non-ASCII characters. For example, § (section sign), or — (emdash), – (endash), etc. You can easily find occurrences of those characters using your favorite editor or IDE.

I appreciate that some occurrences of those symbols are useful in that context and the overall code might read better. However, it seems to hurt portability.

I believe there are 3 options. 1. Do nothing. 2. Change those symbols to their closest ASCII counterparts. 3. Or, if you feel strongly about using those symbols, use the appropriate `\uXXXX` sequences or HTML entities (for javadoc, not for string literals) instead.

If you choose option 2 or 3, you may also want to modify the build by forcing the compiler to produce an error should non-ASCII symbols appear in the future: `javac -encoding US-ASCII`

**Comment by viktorklang** [comment]
The sources are in UTF-8 as specified here: https://github.com/reactive-streams/reactive-streams-jvm/blob/master/build.gradle#L14

**Comment by pavelrappo** [comment]
I completely understand that. I'm not saying that this is a bug or something. It's just that it doesn't seem that essential to have Unicode symbols in this case. It's so easy to make the sources portable. Anyway, I'm fine with you closing this issue. Thanks.

**Comment by viktorklang** [comment]
Not sure I understand the portability issue as UTF-8 seems to be ubiquitous?

**Comment by pavelrappo** [comment]
There is always a portion of environments that are very strict. It would be wonderful if RS sources could be easily viewed and compiled there, using whatever tooling is appropriate. However, I think you have a valid argument. Viktor, once again, feel free to close the issue. It's not a big deal.

**Comment by viktorklang** [comment]
@pavelrappo Is it OK with you if we revisit this when/if there's a concrete case where UTF-8 is not available?

**Comment by pavelrappo** [comment]
That's absolutely fine. Thanks.

**Comment by viktorklang** [comment]
@pavelrappo Perfect. Thank you!
