### ISSUE TITLE
ClassNotFoundException starting bundles `reactive-streams` & `reactive-streams-flow-adapters`

### ISSUE THREAD

**Issue by pedrolamarao** [reactive-streams/reactive-streams-jvm#465]
Starting a set of bundles containing `reactive-streams` and `reactive-streams-flow-adapters` in Apache Felix gives me the following error:

> Caused by: java.lang.ClassNotFoundException: *** Package 'org.reactivestreams' is imported by bundle org.reactivestreams.reactive-streams [9] from bundle org.reactivestreams.reactive-streams [9], but the exported package from bundle org.reactivestreams.reactive-streams [9] does not contain the requested class 'org.reactivestreams.FlowAdapters'. Please verify that the class name is correct in the importing bundle org.reactivestreams.reactive-streams [9] and/or that the exported package is correctly bundled in org.reactivestreams.reactive-streams [9]. ***

If I remove `reactive-streams-flow-adapters` from my configuration the problem does not happen.

Both `reactive-streams-1.0.2.jar` and `reactive-streams-flow-adapters-1.0.2.jar` export package `org.reactivestreams;version="1.0.2"`. Two bundles exporting the same package does not play well with OSGi.

Currently, I am rolling my own `FlowAdapters` because of this.

**Comment by viktorklang** [comment]
Hi Pedro,

Thanks for reporting, this has been addressed already in https://github.com/reactive-streams/reactive-streams-jvm/issues/424 and will ship with 1.0.3
