### ISSUE TITLE
Release a new version?

### ISSUE THREAD

**Issue by viktorklang** [reactive-streams/reactive-streams-jvm#530]
Hi all,

given that Reactive Streams has been relicensed, we should publish a new set of artifacts under the new license.

So the options we have:

  A) Release a 1.0.3 PATCH release with only the license change beyond the 1.0.3 code
  B) Release a 1.0.4 version with the current master/HEAD under the new license
  C) Release a 1.1.0 version with the current master/HEAD under the new license
  D) Release a 2.0.0 version with the current master/HEAD under the new license

@reactive-streams/contributors  Thoughts? Ideas? Preferences?

**Comment by akarnokd** [comment]
B

I'd reserve 2.0.0 for a more substantial expansion of the API.

**Comment by rkuhn** [comment]
Wouldn’t option D artificially split the ecosystem without any real reason to do so? I’m not a lawyer, so as a physicist I’d propose the evidence-based approach of considering this licensing change to be non-breaking until proven otherwise. Proof would have to arrive in the form of relevant complaints, reaching this repository after we do A or B. I’d propose a poll but unfortunately I’m not aware of a useful medium for conveying such a request (i.e. if we ask Twitter we may get an assortment of answers without learning much).

**Comment by simonbasle** [comment]
I'd vote for B as well

**Comment by OlegDokuka** [comment]
B

**Comment by ktoso** [comment]
"I am not a lawyer" prefaced, but... I don't see this change as needing a full major number: B sounds good to me.

**Comment by barchetta** [comment]
Any ETA on this? Thanks!

**Comment by viktorklang** [comment]
@reactive-streams/contributors Seems like the broad consensus is around option B—"1.0.4"

I'm currently in the process of setting up a completely new dev environment, so it would be very much appreciated if another contributor would be able to cut and publish that release. Any takers?

**Comment by barchetta** [comment]
Any news on 1.0.4?

**Comment by Nivedithaneethu** [comment]
Is there any ETA on releasing a new version with the latest license?
Thanks

**Comment by zpd64** [comment]
> @reactive-streams/contributors Seems like the broad consensus is around option B—"1.0.4"
> 
> I'm currently in the process of setting up a completely new dev environment, so it would be very much appreciated if another contributor would be able to cut and publish that release. Any takers?

Hi Viktor, since 1.0.4 is not available yet, could you please give me some tips about how to package this jar locally base on current master/head? we need a version with MIT-0 license, thanks a lot.

**Comment by viktorklang** [comment]
@Nivedithaneethu Apologies for the delay, @rkuhn would you be able to cut this release together with me?

**Comment by rkuhn** [comment]
I don’t think I still have publishing credentials, at least I can’t find them — I haven’t worked in the JVM ecosystem since 2016.

**Comment by viktorklang** [comment]
https://github.com/reactive-streams/reactive-streams-jvm/pull/538/files

**Comment by viktorklang** [comment]
Reactive Streams 1.0.4 has been released.
