### ISSUE TITLE
issue with the License 

### ISSUE THREAD

**Issue by dineshr93** [reactive-streams/reactive-streams-jvm#536]
Hi,
we would like to know this software is free of patents and other issues because this  CC-1.0 license doesn't waive any patents therefore causing potential lawsuits
https://github.com/reactive-streams/reactive-streams-jvm/blob/7207b1b4fb618c0cf17f3391a5e551648c75769d/COPYING#L104

Thanks

**Comment by viktorklang** [comment]
Hi!

The latest license in the main branch has a new license but we have yet to
make a new release from that. I am not a lawyer, so look at the new license
and feel free to build the project from source if that is compliant with
your concerns.

Cheers,
V
-- 
Cheers,
√

**Comment by dineshr93** [comment]
@viktorklang 
Thanks for the info.
Once the upgrade is done I have to notify rxjava to upgrade to new reactive-stream version and then rxandroid and rxkotlin to upgraded to new rxjava 
```

io.reactivex.rxjava2:rxjava:2.1.1 » org.reactivestreams:reactive-streams:1.0.0

io.reactivex.rxjava3:rxkotlin:3.0.1 » io.reactivex.rxjava3:rxjava:3.0.6 » org.reactivestreams:reactive-streams:1.0.3

io.reactivex.rxjava2:rxandroid:2.1.0 » io.reactivex.rxjava2:rxjava:2.2.0 » org.reactivestreams:reactive-streams:1.0.2

io.reactivex.rxjava3:rxandroid:3.0.0 » io.reactivex.rxjava3:rxjava:3.0.6 » org.reactivestreams:reactive-streams:1.0.3


```

**Comment by viktorklang** [comment]
https://github.com/reactive-streams/reactive-streams-jvm/pull/538/files
