### ISSUE TITLE
1.0.4 javadoc on reactive-streams.org missing

### ISSUE THREAD

**Issue by akarnokd** [reactive-streams/reactive-streams-jvm#539]
Looks like the Javadocs did not get published:

http://www.reactive-streams.org/reactive-streams-1.0.4-javadoc/

This works:

http://www.reactive-streams.org/reactive-streams-1.0.3-javadoc/

I didn't catch this because the JDK 11 build errors out due to the unaccessible URL, JDK 8 just issues a warning. In my verification, the JDK 11 build didn't run due to slight misconfiguration in GHA.

**Comment by viktorklang** [comment]
Fixed :)
