### ISSUE TITLE
Empty TCKVerificationSupport.java in the repo

### ISSUE THREAD

**Issue by rsvoboda** [reactive-streams/reactive-streams-jvm#550]
There is an empty [TCKVerificationSupport.java](https://github.com/reactive-streams/reactive-streams-jvm/blob/master/tck-flow/src/test/java/org/reactivestreams/tck/flow/support/TCKVerificationSupport.java) file in `tck-flow` module.

This is probably a leftover from https://github.com/reactive-streams/reactive-streams-jvm/pull/398 work

There is another [TCKVerificationSupport.java](https://github.com/reactive-streams/reactive-streams-jvm/blob/master/tck/src/test/java/org/reactivestreams/tck/flow/support/TCKVerificationSupport.java) file in `tck` module and it is proper Java file.

**Comment by ktoso** [comment]
It'd be great if you can send in a PR to remove it! :)

**Comment by rsvoboda** [comment]
PR https://github.com/reactive-streams/reactive-streams-jvm/pull/552 is ready

**Comment by ktoso** [comment]
Thank you!
