### ISSUE TITLE
add  MonoPublisher and  Closeable interface , developer duplication define Closeable interface

### ISSUE THREAD

**Issue by qinarmy-zoro** [reactive-streams/reactive-streams-jvm#554]
hope add  MonoPublisher and  Closeable interface , developer duplication define Closeable interface

MonoPublisher interface 

```java
/**
 * emit just one element or {@link Throwable}
 */
public interface MonoPublisher<T>  extends Publisher<T> {


}


```
 Closeable interface

```java
public interface Closeable {

    <T> MonoPublisher<T> close();

    boolean isClosed();


}
```

**Comment by He-Pin** [comment]
The problem is in some implementation,  which can maximum emit one element is not specially, eg, Akka stream, or named as Single or Uni.

**Comment by qinarmy-zoro** [comment]
ok ,I just suggest
