### ISSUE TITLE
TCK Upgrade Story

### ISSUE THREAD

**Issue by ktoso** [reactive-streams/reactive-streams-jvm#99]
This issue came up during discussions on the "bring back the TCK" pull request: https://github.com/reactive-streams/reactive-streams/pull/91

In general we need some story about when we change the spec, and the tests, that implementors will be notified about some changed (perhaps *optional*!) behaviour. In the TCK tests which are optional are skipped if they fail to verify currently, this could cause adding optional behaviour in `0.x+1` simply be skipped to be verified, and the implementor may assume "oh good, my impl covers everything". This is not really limited to adding optional tests, but in general behaviour which we can't test for example too.

This issue means to start a discussion about if we want to provide more info for implementors in the TCK itself or simply assume implementors will read changelogs and apply all changes.

One idea on the more extreme side would be that each spec would contain a value `conformsTo() { return Spec_0_4; }`), then if the dependency is updated to `0.5`, we fail the tests listing what has changed... This might be overkill, and simply "please read the change logs" could be our solution here.

I'm interested if you guys see this as a problem that needs solving or we simply document that "if you upgrade, please do read the changelog in detail".

**Comment by rkuhn** [comment]
I’m not convinced that technical measure can fix the problem: patching a string in the source to say “1.2” and then running the verification successfully will always be possible. We need to trust implementors to watch the spec evolve and adapt accordingly. If an unimplemented spec update leads to runtime failures later then we should by definition be in a position to write a test that provokes those, but I estimate that the transition from “everybody does their best” to “the TCK covers everything” will take quite a while.

So, all in all I’m proposing to close this ticket.

**Comment by viktorklang** [comment]
@rkuhn I would even go as far as say that I hope we never need to ship anything beyond 1.0.0.final :)

**Comment by ktoso** [comment]
Just a bump here, the TCK readme contains a section on this which is a TODO (been looking and cleaning it up recently). If we want to write something in that section explicitly it should be before 1.0 I think.

Now we're using methods with `required_` prefixes etc, so just deprecating / removing removing methods  should be reasonable and good enough I feel, opinions?

**Comment by viktorklang** [comment]
Open a PR :)

**Comment by ktoso** [comment]
PR here: https://github.com/reactive-streams/reactive-streams-jvm/pull/246 (rebased and updated)
